In [1]:
## Street trees New York from NYC OpenData: https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh
## 684k rows 

## Started by Mairead 25/10/2020
## SORT groupby
## using https://stackoverflow.com/questions/27018622/pandas-groupby-sort-descending-order
import requests
import pandas as pd

## 2015_Street_Tree_Census
## C:\Users\manif\Documents\Documents\NCIRL\Project\Data\2015_Street_Tree_Census.csv

all_Trees = pd.read_csv (r'C:\Users\manif\Documents\Documents\NCIRL\Project\Data\2015_Street_Tree_Census.csv')   #read the csv file (put 'r' before the path string to address any special characters in the path, such as '\'). Don't forget to put the file name at the end of the path + ".csv"
#print ("all_Trees", all_Trees.head(20))
rows = len(all_Trees)
print("rows of all_Trees", rows)  ## 683788 rows x 45 columns

colNames = all_Trees.columns.tolist()

grouped = all_Trees.groupby("nta_name")["tree_id"].count().sort_values(ascending=False)
print("grouped", grouped)

rows of all_Trees 683788
grouped nta_name
Annadale-Huguenot-Prince's Bay-Eltingville    12969
Great Kills                                   10734
Bayside-Bayside Hills                          9780
East New York                                  9607
Rossville-Woodrow                              9251
                                              ...
Manhattanville                                  913
Parkchester                                     790
Starrett City                                   688
West Brighton                                   481
Stuyvesant Town-Cooper Village                  447
Name: tree_id, Length: 188, dtype: int64

In [2]:
grouped2 = all_Trees.groupby("nta_name")["nta_name"].count().sort_values(ascending=False)
print("grouped2", grouped2)

grouped2 nta_name
Annadale-Huguenot-Prince's Bay-Eltingville    12969
Great Kills                                   10734
Bayside-Bayside Hills                          9780
East New York                                  9607
Rossville-Woodrow                              9251
                                              ...
Manhattanville                                  913
Parkchester                                     790
Starrett City                                   688
West Brighton                                   481
Stuyvesant Town-Cooper Village                  447
Name: nta_name, Length: 188, dtype: int64

In [3]:
print ("shape or no of rows for all_Trees", all_Trees.shape)
all_Trees.head()

shape or no of rows for all_Trees (683788, 45)

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
0,180683,348711,08/27/2015,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,"4,073,900",New York,40.723092,-73.844215,"1,027,431.15","202,756.77",29.0,739.0,4052307.0,4.022210e+09
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,"4,097,300",New York,40.794111,-73.818679,"1,034,455.70","228,644.84",19.0,973.0,4101931.0,4.044750e+09
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,"3,044,900",New York,40.717581,-73.936608,"1,001,822.83","200,716.89",34.0,449.0,3338310.0,3.028870e+09
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,"3,044,900",New York,40.713537,-73.934456,"1,002,420.36","199,244.25",34.0,449.0,3338342.0,3.029250e+09
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,"3,016,500",New York,40.666778,-73.975979,"990,913.78","182,202.43",39.0,165.0,3025654.0,3.010850e+09

In [4]:
list_tracts = all_Trees['boro_ct'].nunique()
list_tracts ## there are unique borough districts tracts stats for New York

2152

In [5]:
groupedTrees = all_Trees.groupby("spc_common")["tree_id"].count().sort_values(ascending=False)

print("groupedTrees", groupedTrees)

groupedTrees spc_common
London planetree    87014
honeylocust         64264
Callery pear        58931
pin oak             53185
Norway maple        34189
                    ...
black pine             37
pitch pine             33
Osage-orange           29
Scots pine             25
Virginia pine          10
Name: tree_id, Length: 132, dtype: int64

In [6]:
groupedTrees2 = all_Trees.groupby("spc_common")["spc_common"].count().sort_values(ascending=False)

print("groupedTrees2", groupedTrees2)

groupedTrees2 spc_common
London planetree    87014
honeylocust         64264
Callery pear        58931
pin oak             53185
Norway maple        34189
                    ...
black pine             37
pitch pine             33
Osage-orange           29
Scots pine             25
Virginia pine          10
Name: spc_common, Length: 132, dtype: int64

In [7]:
colNames = all_Trees.columns.tolist()
print("col names of all_Trees is this", colNames) ## census_tract (3rd last column) is 
## number and should be 5 digits and needs filling with leading zeros.

col names of all_Trees is this ['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam', 'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward', 'guards', 'sidewalk', 'user_type', 'problems', 'root_stone', 'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other', 'brch_light', 'brch_shoe', 'brch_other', 'address', 'postcode', 'zip_city', 'community board', 'borocode', 'borough', 'cncldist', 'st_assem', 'st_senate', 'nta', 'nta_name', 'boro_ct', 'state', 'latitude', 'longitude', 'x_sp', 'y_sp', 'council district', 'census tract', 'bin', 'bbl']

In [8]:
all_Trees.columns = ['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam', 'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward', 'guards', 'sidewalk', 'user_type', 'problems', 'root_stone', 'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other', 'brch_light', 'brch_shoe', 'brch_other', 'address', 'postcode', 'zip_city', 'community_board', 'borocode', 'borough', 'cncldist', 'st_assem', 'st_senate', 'nta', 'nta_name', 'boro_ct', 'state', 'latitude', 'longitude', 'x_sp', 'y_sp', 'council_district', 'census_tract', 'bin', 'bbl',]

In [9]:
pd.set_option('display.max_columns', None)
#all_Trees.loc[all_Trees['census_tract'] == 61003.0]
all_Trees.loc[:,["nta_name", "nta", "boro_ct", "census_tract"]].head(100)

              nta_name   nta    boro_ct  census_tract
0         Forest Hills  QN17  4,073,900         739.0
1           Whitestone  QN49  4,097,300         973.0
2    East Williamsburg  BK90  3,044,900         449.0
3    East Williamsburg  BK90  3,044,900         449.0
4   Park Slope-Gowanus  BK37  3,016,500         165.0
..                 ...   ...        ...           ...
95           Gravesend  BK26  3,037,401       37401.0
96        Forest Hills  QN17  4,070,700         707.0
97        Clinton Hill  BK69  3,019,100         191.0
98     Upper West Side  MN12  1,016,500         165.0
99     Upper West Side  MN12  1,016,500         165.0

[100 rows x 4 columns]

In [10]:
pd.set_option('display.max_columns', None)
#all_Trees.loc[all_Trees['census_tract'] == 61003.0]
all_Trees.loc[:,["nta_name", "boro_ct", "census_tract"]].head(100)

              nta_name    boro_ct  census_tract
0         Forest Hills  4,073,900         739.0
1           Whitestone  4,097,300         973.0
2    East Williamsburg  3,044,900         449.0
3    East Williamsburg  3,044,900         449.0
4   Park Slope-Gowanus  3,016,500         165.0
..                 ...        ...           ...
95           Gravesend  3,037,401       37401.0
96        Forest Hills  4,070,700         707.0
97        Clinton Hill  3,019,100         191.0
98     Upper West Side  1,016,500         165.0
99     Upper West Side  1,016,500         165.0

[100 rows x 3 columns]

In [11]:
print("No. of columns containing null values")
print(len(all_Trees.columns[all_Trees.isna().any()]))

print("No. of columns not containing null values")
print(len(all_Trees.columns[all_Trees.notna().all()]))

print("Total no. of columns in the dataframe")
print(len(all_Trees.columns))

No. of columns containing null values
11
No. of columns not containing null values
34
Total no. of columns in the dataframe
45

In [12]:
####THE "census_tract" FILE DOESN'T SEEM TO BE EXACT. THE TRACT id FROM THE SHAPE FILE 
#### IS MORE RELIABLE AND IT IS DERIEVED FROM THE THE LATITUDE AND LONGITUDE SETTINGS
all_Trees[all_Trees['census_tract'].isna()][[
    "address","nta","nta_name", "boro_ct", "census_tract"]]

,address,nta,nta_name,boro_ct,census_tract
8,65 JEROME AVENUE,SI14,Grasmere-Arrochar-Ft. Wadsworth,"5,006,400",NaN
68,1 MORNINGSIDE DRIVE,MN09,Morningside Heights,"1,019,701",NaN
213,137 EAST 36 STREET,MN20,Murray Hill-Kips Bay,"1,008,000",NaN
235,2-008 BEACH 108 STREET,QN10,Breezy Point-Belle Harbor-Rockaway Park-Broad ...,"4,093,800",NaN
258,2-008 BEACH 108 STREET,QN10,Breezy Point-Belle Harbor-Rockaway Park-Broad ...,"4,093,800",NaN
...,...,...,...,...,...
683425,3 LINCOLN PLAZA,MN14,Lincoln Square,"1,014,900",NaN
683592,137 EAST 36 STREET,MN20,Murray Hill-Kips Bay,"1,008,000",NaN
683605,2-008 BEACH 108 STREET,QN10,Breezy Point-Belle Harbor-Rockaway Park-Broad ...,"4,093,800",NaN
683626,1-094 BEACH 74 STREET,QN12,Hammels-Arverne-Edgemere,"4,095,400",NaN
683660,2-008 BEACH 108 STREET,QN10,Breezy Point-Belle Harbor-Rockaway Park-Broad ...,"4,093,800",NaN

In [13]:
all_Trees.at[2514,'census_tract']=69702.0

In [14]:
all_Trees.loc[all_Trees['nta']=="MN25"][[
    "address","nta","nta_name", "boro_ct", "census_tract"
]]

,address,nta,nta_name,boro_ct,census_tract
266,120 LIBERTY STREET,MN25,Battery Park City-Lower Manhattan,"1,001,300",13.0
398,124 LIBERTY STREET,MN25,Battery Park City-Lower Manhattan,"1,001,300",13.0
449,21 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
736,21 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
1146,21 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
...,...,...,...,...,...
683454,2 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
683488,21 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
683497,21 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
683710,377 RECTOR PLACE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0
683764,21 SOUTH END AVENUE,MN25,Battery Park City-Lower Manhattan,"1,031,704",31704.0

all_Trees.at[1970,'census_tract']=29102.0

In [15]:
all_Trees["census_tract"]

0           739.0
1           973.0
2           449.0
3           449.0
4           165.0
           ...
683783      519.0
683784      707.0
683785      201.0
683786    23502.0
683787     1341.0
Name: census_tract, Length: 683788, dtype: float64

In [16]:
##print(all_Trees['census_tract'].apply(lambda x: str(x).zfill(7)[:-2])
all_Trees['census_tract'] = all_Trees['census_tract'].apply(lambda x: str(x).zfill(8)[:-2]) 
## removing .and zero and converting to string with leading zeros

In [17]:
all_Trees['census_tract']

0         000739
1         000973
2         000449
3         000449
4         000165
           ...
683783    000519
683784    000707
683785    000201
683786    023502
683787    001341
Name: census_tract, Length: 683788, dtype: object

In [18]:
all_Trees[366:370]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,steward,guards,sidewalk,user_type,problems,root_stone,root_grate,root_other,trunk_wire,trnk_light,trnk_other,brch_light,brch_shoe,brch_other,address,postcode,zip_city,community_board,borocode,borough,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,council_district,census_tract,bin,bbl
366,166718,319654,08/22/2015,18,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,NoDamage,Volunteer,"RootOther,WiresRope,BranchLights",No,No,Yes,Yes,No,No,Yes,No,No,80-050 BELL BOULEVARD,11427,Queens Village,411,4,Queens,23,24,11,QN42,Oakland Gardens,"4,129,102",New York,40.732878,-73.754648,"1,052,247.85","206,378.96",23.0,129102,4164766.0,4.077890e+09
367,138199,226453,08/12/2015,6,0,OnCurb,Alive,Poor,Acer platanoides,Norway maple,None,None,Damage,Volunteer,None,No,No,No,No,No,No,No,No,No,1285 DEAN STREET,11216,Brooklyn,308,3,Brooklyn,36,56,25,BK61,Crown Heights North,"3,031,300",New York,40.676740,-73.946522,"999,083.49","185,835.49",36.0,000313,3030129.0,3.012080e+09
368,166477,348128,08/22/2015,22,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,Damage,Volunteer,None,No,No,No,No,No,No,No,No,No,78-020 KEW FOREST LANE,11375,Forest Hills,406,4,Queens,29,28,15,QN17,Forest Hills,"4,076,902",New York,40.714499,-73.833296,"1,030,463.61","199,631.65",NaN,00000n,NaN,NaN
369,178550,108404,08/26/2015,12,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,38 MORNINGSIDE AVENUE,10026,New York,109,1,Manhattan,7,70,30,MN09,Morningside Heights,"1,019,701",New York,40.806903,-73.957399,"996,043.56","233,256.60",9.0,020102,1059082.0,1.019448e+09

In [19]:
import geopandas as gpd ## completing for tracts


nyc_data_points = gpd.GeoDataFrame(all_Trees, geometry=gpd.points_from_xy(all_Trees.longitude, all_Trees.latitude), crs='EPSG:4326')
nyc_data_points

nyc_shape = "cb_2018_36_tract_500k.shp"  # load shape file 

nyc_map = gpd.read_file(nyc_shape)

points_in_map = gpd.sjoin(nyc_data_points.to_crs('EPSG:4269'), 
                         nyc_map, 
                         how='inner', 
                         op='within')

In [20]:
nyc_data_points[1:5]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,steward,guards,sidewalk,user_type,problems,root_stone,root_grate,root_other,trunk_wire,trnk_light,trnk_other,brch_light,brch_shoe,brch_other,address,postcode,zip_city,community_board,borocode,borough,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,council_district,census_tract,bin,bbl,geometry
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,147-074 7 AVENUE,11357,Whitestone,407,4,Queens,19,27,11,QN49,Whitestone,"4,097,300",New York,40.794111,-73.818679,"1,034,455.70","228,644.84",19.0,000973,4101931.0,4.044750e+09,POINT (-73.81868 40.79411)
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,1or2,None,Damage,Volunteer,None,No,No,No,No,No,No,No,No,No,390 MORGAN AVENUE,11211,Brooklyn,301,3,Brooklyn,34,50,18,BK90,East Williamsburg,"3,044,900",New York,40.717581,-73.936608,"1,001,822.83","200,716.89",34.0,000449,3338310.0,3.028870e+09,POINT (-73.93661 40.71758)
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,None,None,Damage,Volunteer,Stones,Yes,No,No,No,No,No,No,No,No,1027 GRAND STREET,11211,Brooklyn,301,3,Brooklyn,34,53,18,BK90,East Williamsburg,"3,044,900",New York,40.713537,-73.934456,"1,002,420.36","199,244.25",34.0,000449,3338342.0,3.029250e+09,POINT (-73.93446 40.71354)
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,None,None,Damage,Volunteer,Stones,Yes,No,No,No,No,No,No,No,No,603 6 STREET,11215,Brooklyn,306,3,Brooklyn,39,44,21,BK37,Park Slope-Gowanus,"3,016,500",New York,40.666778,-73.975979,"990,913.78","182,202.43",39.0,000165,3025654.0,3.010850e+09,POINT (-73.97598 40.66678)

In [21]:
points_in_map[1:5]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,steward,guards,sidewalk,user_type,problems,root_stone,root_grate,root_other,trunk_wire,trnk_light,trnk_other,brch_light,brch_shoe,brch_other,address,postcode,zip_city,community_board,borocode,borough,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,council_district,census_tract,bin,bbl,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
333,179127,348611,08/27/2015,32,0,OnCurb,Alive,Good,Liriodendron tulipifera,tulip-poplar,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 QUEENS BOULEVARD,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720999,-73.842365,"1,027,945.36","201,995.39",29.0,000739,4052426.0,4.022250e+09,POINT (-73.84237 40.72100),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0
583,180699,348714,08/27/2015,21,0,OnCurb,Alive,Fair,Gleditsia triacanthos var. inermis,honeylocust,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,69-067 108 STREET,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723119,-73.844461,"1,027,363.10","202,766.53",29.0,000739,4052307.0,4.022210e+09,POINT (-73.84446 40.72312),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0
623,180679,348711,08/27/2015,3,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,None,None,Damage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,108-021 70 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723229,-73.843754,"1,027,558.82","202,807.01",29.0,000739,4052322.0,4.022210e+09,POINT (-73.84375 40.72323),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0
1063,179181,348542,08/27/2015,7,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-019 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720882,-73.840993,"1,028,325.64","201,953.29",29.0,000739,4052428.0,4.022250e+09,POINT (-73.84099 40.72088),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0

In [22]:
nyc_map[1:5]

,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
1,36,021,000402,1400000US36021000402,36021000402,4.02,CT,42294908,1437327,"POLYGON ((-73.72088 42.45322, -73.71799 42.470..."
2,36,023,970700,1400000US36023970700,36023970700,9707,CT,2082176,0,"POLYGON ((-76.20049 42.61248, -76.19596 42.612..."
3,36,081,046200,1400000US36081046200,36081046200,462,CT,249611,0,"POLYGON ((-73.79203 40.71107, -73.79101 40.711..."
4,36,081,048100,1400000US36081048100,36081048100,481,CT,139052,0,"POLYGON ((-73.88799 40.74355, -73.88621 40.743..."

In [23]:
## opened a copy of cb_2018_36_tract_500k.dbf in Excel and save as a csv file. (36 is code for New York)
## the index_right gives aligns with index in csv file. 
census_tract_df = nyc_map
print("census tract info from New York dbf file saved as a csv file")
census_tract_df[1:5]

census tract info from New York dbf file saved as a csv file

,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
1,36,021,000402,1400000US36021000402,36021000402,4.02,CT,42294908,1437327,"POLYGON ((-73.72088 42.45322, -73.71799 42.470..."
2,36,023,970700,1400000US36023970700,36023970700,9707,CT,2082176,0,"POLYGON ((-76.20049 42.61248, -76.19596 42.612..."
3,36,081,046200,1400000US36081046200,36081046200,462,CT,249611,0,"POLYGON ((-73.79203 40.71107, -73.79101 40.711..."
4,36,081,048100,1400000US36081048100,36081048100,481,CT,139052,0,"POLYGON ((-73.88799 40.74355, -73.88621 40.743..."

In [24]:
census_tract_df["TRACTCE"][1:5]

1    000402
2    970700
3    046200
4    048100
Name: TRACTCE, dtype: object

In [25]:
census_tract_df["COUNTYFP"][1:5]

1    021
2    023
3    081
4    081
Name: COUNTYFP, dtype: object

In [26]:
census_tract_df.dtypes

STATEFP       object
COUNTYFP      object
TRACTCE       object
AFFGEOID      object
GEOID         object
NAME          object
LSAD          object
ALAND          int64
AWATER         int64
geometry    geometry
dtype: object

In [27]:
points_in_map.dtypes

tree_id                int64
block_id               int64
created_at            object
tree_dbh               int64
stump_diam             int64
curb_loc              object
status                object
health                object
spc_latin             object
spc_common            object
steward               object
guards                object
sidewalk              object
user_type             object
problems              object
root_stone            object
root_grate            object
root_other            object
trunk_wire            object
trnk_light            object
trnk_other            object
brch_light            object
brch_shoe             object
brch_other            object
address               object
postcode               int64
zip_city              object
community_board        int64
borocode               int64
borough               object
cncldist               int64
st_assem               int64
st_senate              int64
nta                   object
nta_name              object
boro_ct               object
state                 object
latitude             float64
longitude            float64
x_sp                  object
y_sp                  object
council_district     float64
census_tract          object
bin                  float64
bbl                  float64
geometry            geometry
index_right            int64
STATEFP               object
COUNTYFP              object
TRACTCE               object
AFFGEOID              object
GEOID                 object
NAME                  object
LSAD                  object
ALAND                  int64
AWATER                 int64
dtype: object

In [28]:
print("no of columns and rows", points_in_map.shape)

no of columns and rows (683693, 56)

In [29]:
points_in_map2 = points_in_map.join(census_tract_df[['STATEFP','COUNTYFP','TRACTCE']],on='index_right', lsuffix='_left') 
points_in_map2[1:10]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,steward,guards,sidewalk,user_type,problems,root_stone,root_grate,root_other,trunk_wire,trnk_light,trnk_other,brch_light,brch_shoe,brch_other,address,postcode,zip_city,community_board,borocode,borough,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,council_district,census_tract,bin,bbl,geometry,index_right,STATEFP_left,COUNTYFP_left,TRACTCE_left,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,STATEFP,COUNTYFP,TRACTCE
333,179127,348611,08/27/2015,32,0,OnCurb,Alive,Good,Liriodendron tulipifera,tulip-poplar,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 QUEENS BOULEVARD,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720999,-73.842365,"1,027,945.36","201,995.39",29.0,000739,4052426.0,4.022250e+09,POINT (-73.84237 40.72100),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
583,180699,348714,08/27/2015,21,0,OnCurb,Alive,Fair,Gleditsia triacanthos var. inermis,honeylocust,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,69-067 108 STREET,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723119,-73.844461,"1,027,363.10","202,766.53",29.0,000739,4052307.0,4.022210e+09,POINT (-73.84446 40.72312),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
623,180679,348711,08/27/2015,3,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,None,None,Damage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,108-021 70 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723229,-73.843754,"1,027,558.82","202,807.01",29.0,000739,4052322.0,4.022210e+09,POINT (-73.84375 40.72323),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
1063,179181,348542,08/27/2015,7,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-019 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720882,-73.840993,"1,028,325.64","201,953.29",29.0,000739,4052428.0,4.022250e+09,POINT (-73.84099 40.72088),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
1255,179177,348542,08/27/2015,5,0,OnCurb,Alive,Poor,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,"TrunkOther,BranchOther",No,No,No,No,No,Yes,No,No,Yes,109-006 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720732,-73.841502,"1,028,184.88","201,898.34",29.0,000739,4052429.0,4.022260e+09,POINT (-73.84150 40.72073),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
1518,179126,348610,08/27/2015,9,0,OnCurb,Alive,Fair,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720780,-73.841686,"1,028,133.82","201,915.86",29.0,000739,4052425.0,4.022250e+09,POINT (-73.84169 40.72078),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
5551,180669,348711,08/27/2015,12,0,OnCurb,Alive,Fair,Acer platanoides 'Crimson King',crimson king maple,None,None,NoDamage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,108-057 70 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723594,-73.842529,"1,027,898.28","202,940.59",29.0,000739,4052317.0,4.022210e+09,POINT (-73.84253 40.72359),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
8250,179180,348542,08/27/2015,8,0,OnCurb,Alive,Fair,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-019 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720857,-73.841077,"1,028,302.54","201,944.27",29.0,000739,4052428.0,4.022250e+09,POINT (-73.84108 40.72086),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900
8344,179124,348610,08/27/2015,11,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720849,-73.841453,"1,028,198.38","201,941.04",29.0,000739,4052425.0,4.022250e+09,POINT (-73.84145 40.72085),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,36,081,073900

In [30]:
points_in_map_short = points_in_map2.filter(['spc_common','address','boro_ct', 'nta', 'nta_name', 'census_tract', 'COUNTYFP', 'TRACTCE', 'geometry', 'index_right', 'ALAND', ], axis=1)

In [31]:
import pandas as pd
pd.set_option('display.max_rows', 500)
points_in_map_short.head()

,spc_common,address,boro_ct,nta,nta_name,census_tract,COUNTYFP,TRACTCE,geometry,index_right,ALAND
0,red maple,108-005 70 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84422 40.72309),569,224293
333,tulip-poplar,109-005 QUEENS BOULEVARD,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84237 40.72100),569,224293
583,honeylocust,69-067 108 STREET,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84446 40.72312),569,224293
623,Callery pear,108-021 70 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84375 40.72323),569,224293
1063,Norway maple,109-019 72 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84099 40.72088),569,224293

In [32]:
groupedTract_count = points_in_map_short.groupby(['COUNTYFP','TRACTCE','ALAND']).size().reset_index(name='treesStats')
#df2 = df.rename({'a': 'X', 'b': 'Y'}, axis=1) 
groupedTract_count

     COUNTYFP TRACTCE    ALAND  treesStats
0         005  000200   479463         377
1         005  000400   770689         478
2         005  001600   485079         523
3         005  001900  1668013         508
4         005  002000   395564         422
...       ...     ...      ...         ...
2160      119  000203   472670           4
2161      119  001503   775771           5
2162      119  002600  1471967           4
2163      119  002900   368883           1
2164      119  005500  3490858           4

[2165 rows x 4 columns]

In [33]:
groupedTract_mean = groupedTract_count["treesStats"].mean()
print("mean",groupedTract_mean)
groupedTract_min = groupedTract_count["treesStats"].min()
print("min", groupedTract_min)
groupedTract_max = groupedTract_count["treesStats"].max()
print("max", groupedTract_max)

mean 315.7935334872979
min 1
max 3778

In [34]:
import numpy as np
groupedTract_count["trees"] = np.where(groupedTract_count.treesStats < groupedTract_mean, "low", "high")
groupedTract_count[1:6]

  COUNTYFP TRACTCE    ALAND  treesStats trees
1      005  000400   770689         478  high
2      005  001600   485079         523  high
3      005  001900  1668013         508  high
4      005  002000   395564         422  high
5      005  002300   104645          53   low

In [83]:
groupedTract_count.shape

(2165, 5)

In [35]:
## join census data to tree data 
## https://kodlogs.com/38097/len-left_on-must-equal-the-number-of-levels-in-the-index-of-right#:~:text=pages%20in%20html-,Len(left_on)%20must%20equal%20the%20number%20of%20levels%20in,the%20index%20of%20%22right%22.
points_in_map_withTrees = pd.merge(left = points_in_map, right = groupedTract_count, how = 'inner', on = ['COUNTYFP', 'TRACTCE', 'ALAND'] )
points_in_map_withTrees[1:10]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,steward,guards,sidewalk,user_type,problems,root_stone,root_grate,root_other,trunk_wire,trnk_light,trnk_other,brch_light,brch_shoe,brch_other,address,postcode,zip_city,community_board,borocode,borough,cncldist,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp,council_district,census_tract,bin,bbl,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,treesStats,trees
1,179127,348611,08/27/2015,32,0,OnCurb,Alive,Good,Liriodendron tulipifera,tulip-poplar,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 QUEENS BOULEVARD,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720999,-73.842365,"1,027,945.36","201,995.39",29.0,000739,4052426.0,4.022250e+09,POINT (-73.84237 40.72100),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
2,180699,348714,08/27/2015,21,0,OnCurb,Alive,Fair,Gleditsia triacanthos var. inermis,honeylocust,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,69-067 108 STREET,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723119,-73.844461,"1,027,363.10","202,766.53",29.0,000739,4052307.0,4.022210e+09,POINT (-73.84446 40.72312),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
3,180679,348711,08/27/2015,3,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,None,None,Damage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,108-021 70 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723229,-73.843754,"1,027,558.82","202,807.01",29.0,000739,4052322.0,4.022210e+09,POINT (-73.84375 40.72323),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
4,179181,348542,08/27/2015,7,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-019 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720882,-73.840993,"1,028,325.64","201,953.29",29.0,000739,4052428.0,4.022250e+09,POINT (-73.84099 40.72088),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
5,179177,348542,08/27/2015,5,0,OnCurb,Alive,Poor,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,"TrunkOther,BranchOther",No,No,No,No,No,Yes,No,No,Yes,109-006 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720732,-73.841502,"1,028,184.88","201,898.34",29.0,000739,4052429.0,4.022260e+09,POINT (-73.84150 40.72073),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
6,179126,348610,08/27/2015,9,0,OnCurb,Alive,Fair,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720780,-73.841686,"1,028,133.82","201,915.86",29.0,000739,4052425.0,4.022250e+09,POINT (-73.84169 40.72078),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
7,180669,348711,08/27/2015,12,0,OnCurb,Alive,Fair,Acer platanoides 'Crimson King',crimson king maple,None,None,NoDamage,TreesCount Staff,None,No,No,No,No,No,No,No,No,No,108-057 70 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.723594,-73.842529,"1,027,898.28","202,940.59",29.0,000739,4052317.0,4.022210e+09,POINT (-73.84253 40.72359),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
8,179180,348542,08/27/2015,8,0,OnCurb,Alive,Fair,Acer platanoides,Norway maple,None,None,NoDamage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-019 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720857,-73.841077,"1,028,302.54","201,944.27",29.0,000739,4052428.0,4.022250e+09,POINT (-73.84108 40.72086),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high
9,179124,348610,08/27/2015,11,0,OnCurb,Alive,Good,Acer platanoides,Norway maple,None,None,Damage,TreesCount Staff,Stones,Yes,No,No,No,No,No,No,No,No,109-005 72 AVENUE,11375,Forest Hills,406,4,Queens,29,28,16,QN17,Forest Hills,"4,073,900",New York,40.720849,-73.841453,"1,028,198.38","201,941.04",29.0,000739,4052425.0,4.022250e+09,POINT (-73.84145 40.72085),569,36,081,073900,1400000US36081073900,36081073900,739,CT,224293,0,395,high

In [36]:
points_in_map_withTrees_short = pd.merge(left = points_in_map_short, right = groupedTract_count, how = 'inner', on = ['COUNTYFP', 'TRACTCE', 'ALAND'] )
points_in_map_withTrees_short[1:10]

,spc_common,address,boro_ct,nta,nta_name,census_tract,COUNTYFP,TRACTCE,geometry,index_right,ALAND,treesStats,trees
1,tulip-poplar,109-005 QUEENS BOULEVARD,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84237 40.72100),569,224293,395,high
2,honeylocust,69-067 108 STREET,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84446 40.72312),569,224293,395,high
3,Callery pear,108-021 70 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84375 40.72323),569,224293,395,high
4,Norway maple,109-019 72 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84099 40.72088),569,224293,395,high
5,Norway maple,109-006 72 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84150 40.72073),569,224293,395,high
6,Norway maple,109-005 72 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84169 40.72078),569,224293,395,high
7,crimson king maple,108-057 70 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84253 40.72359),569,224293,395,high
8,Norway maple,109-019 72 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84108 40.72086),569,224293,395,high
9,Norway maple,109-005 72 AVENUE,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84145 40.72085),569,224293,395,high

In [37]:
points_in_map_withTrees_short = points_in_map_withTrees.filter(['spc_common','address', 'borough', 'boro_ct', 'nta', 'nta_name', 'census_tract', 'COUNTYFP', 'TRACTCE', 'geometry', 'index_right', 'ALAND', 'treesStats', 'trees' ], axis=1)

In [38]:
points_in_map_withTrees_short.head()

,spc_common,address,borough,boro_ct,nta,nta_name,census_tract,COUNTYFP,TRACTCE,geometry,index_right,ALAND,treesStats,trees
0,red maple,108-005 70 AVENUE,Queens,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84422 40.72309),569,224293,395,high
1,tulip-poplar,109-005 QUEENS BOULEVARD,Queens,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84237 40.72100),569,224293,395,high
2,honeylocust,69-067 108 STREET,Queens,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84446 40.72312),569,224293,395,high
3,Callery pear,108-021 70 AVENUE,Queens,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84375 40.72323),569,224293,395,high
4,Norway maple,109-019 72 AVENUE,Queens,"4,073,900",QN17,Forest Hills,000739,081,073900,POINT (-73.84099 40.72088),569,224293,395,high

In [37]:
## should have taken in NYC_CSV_Mar6th_after_shape.csv instead of the AllCleanedandShapedCSV_?? file which needs to be filtered

url_AllCities = 'https://raw.githubusercontent.com/maireadmanifold/files/main/NYC_CSV_Mar8th_after_shape.csv'
df_AllCities = pd.read_csv(url_AllCities, error_bad_lines=False, index_col=0)
print("no of rows in df_AllCities", df_AllCities.shape)

no of rows in df_AllCities (2140, 74)

In [38]:
df_ML_NYC = df_AllCities[df_AllCities['STATEFP'] == 36]
print("now of rows in df_ML_NYC: ", df_ML_NYC.shape)

now of rows in df_ML_NYC:  (2140, 74)

In [39]:
print("no of rows in the df_ML_NYC data file: ", df_ML_NYC.shape)

no of rows in the df_ML_NYC data file:  (2140, 74)

In [40]:
##df_ML_Dallas_with_index_right['COUNTYFP'].unique() All_CSVs_11['Statefp'].unique()
df_ML_NYC['COUNTYFP'].unique()

array([  5,  47,  59,  61,  81,  85, 119], dtype=int64)

In [41]:
df_ML_NYC.head()

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP,index,AFFGEOID,GEOID
0,"Census Tract 429.02, Bronx County, New York",25.1,39.5,4.5,92.0,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,18.7,18.9,44.7,0.0,37.7,37.7,11.9,37.6,37.0,71.6,97.1,0.0,2.1,77.2,3.2,4.4,5.5,9.8,2.05,5.7,23.0,43.3,0.0,0.0,14.0,9.9,13.7,2.3,0.2,14.0,901,low,82.476912,72.502944,97.848584,73.337346,148.366778,112.093990,98.160320,1496.191617,106.871338,90.080656,96.608555,5,42902,36,2436,1400000US36005042902,36005042902
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.377760,1496.191617,142.294608,97.118208,97.748479,5,33000,36,1667,1400000US36005033000,36005033000
2,"Census Tract 358, Bronx County, New York",23.1,22.8,6.6,84.0,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,35.2,0.0,15.5,8.4,70.1,70.1,4.3,5.5,9.8,0.0,95.8,1.6,3.5,3.1,0.0,0.9,2.9,65.9,3.34,1.9,30.7,1.1,0.0,0.0,18.6,5.4,19.0,0.0,0.0,10.4,1667,low,141.872662,109.079761,105.321965,105.806697,115.169251,118.468611,188.010277,1496.191617,163.281225,115.063963,104.303041,5,35800,36,4048,1400000US36005035800,36005035800
3,"Census Tract 371, Bronx County, New York",20.2,48.9,3.8,54.0,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,33.0,7.5,53.6,1.4,40.8,40.8,6.2,24.2,0.0,29.4,95.1,0.0,1.5,63.2,0.0,1.8,19.9,10.4,4.02,3.5,41.1,0.0,5.5,0.0,30.9,6.2,20.5,1.1,0.0,27.3,2504,high,96.560279,88.540912,124.649755,70.359553,94.073286,65.815895,100.891534,1496.191617,116.228428,86.561881,104.873003,5,37100,36,4049,1400000US36005037100,36005037100
4,"Census Tract 385, Bronx County, New York",38.9,38.6,4.0,49.0,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,18.9,9.7,60.5,0.4,21.8,21.8,16.8,44.6,55.0,59.5,91.5,52.7,4.0,72.9,0.0,4.4,12.7,1.6,2.19,2.9,26.7,26.9,0.0,0.0,0.0,12.4,12.2,0.2,0.0,8.3,3443,high,57.188096,62.847123,59.794228,73.704818,112.430046,85.602057,111.046050,1496.191617,111.884065,98.525718,106.867870,5,38500,36,2429,1400000US36005038500,36005038500

In [42]:
df_ML_NYC["TRACTCE"] = df_ML_NYC["TRACTCE"].apply(lambda x: '{0:0>6}'.format(x))
df_ML_NYC["COUNTYFP"] = df_ML_NYC["COUNTYFP"].apply(lambda x: '{0:0>3}'.format(x))

In [45]:
##TotalPopoandTotalFamHHs_10th.csv
url_ALLPopandHHs = 'https://raw.githubusercontent.com/maireadmanifold/files/main/TotalPopoandTotalFamHHs_Mar8th.csv'
df_ML_ALL_PopandHHs = pd.read_csv(url_ALLPopandHHs, error_bad_lines=False, index_col=0)
df_ML_NYC_PopandHHs = df_ML_ALL_PopandHHs[df_ML_ALL_PopandHHs['State'] == 36]
print("no of rows in df_ML_NYC_with_CrimeStats", df_ML_NYC_PopandHHs.shape)

no of rows in df_ML_NYC_with_CrimeStats (2140, 6)

In [46]:
df_ML_NYC_PopandHHs["TRACTCE"] = df_ML_NYC_PopandHHs["Tract"].apply(lambda x: '{0:0>6}'.format(x))
df_ML_NYC_PopandHHs["COUNTYFP"] = df_ML_NYC_PopandHHs["County"].apply(lambda x: '{0:0>3}'.format(x))
df_ML_NYC_PopandHHs["STATEFP"] = df_ML_NYC_PopandHHs["State"].apply(lambda x: '{0:0>2}'.format(x))

<ipython-input-46-9dfa198815f0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ML_NYC_PopandHHs["TRACTCE"] = df_ML_NYC_PopandHHs["Tract"].apply(lambda x: '{0:0>6}'.format(x))
<ipython-input-46-9dfa198815f0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ML_NYC_PopandHHs["COUNTYFP"] = df_ML_NYC_PopandHHs["County"].apply(lambda x: '{0:0>3}'.format(x))
<ipython-input-46-9dfa198815f0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ML_NYC_PopandHHs["STATEFP"] = df_ML_NYC_PopandHHs["State"].apply(lambda x: '{0:0>2}'.format(x))

In [47]:
df_ML_NYC_PopandHHs[1:4]

,State,County,Tract,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,crimeStats,TRACTCE,COUNTYFP,STATEFP
1,36,5,33000,5885,1433,2490,033000,005,36
2,36,5,35800,8054,1885,1667,035800,005,36
3,36,5,37100,4322,888,2504,037100,005,36

In [48]:
df_ML_NYC_PopandHHs["TRACTCE"] = df_ML_NYC_PopandHHs["TRACTCE"].apply(lambda x: '{0:0>6}'.format(x))
df_ML_NYC_PopandHHs["COUNTYFP"] = df_ML_NYC_PopandHHs["COUNTYFP"].apply(lambda x: '{0:0>3}'.format(x))
df_ML_NYC_PopandHHs["STATEFP"] = df_ML_NYC_PopandHHs["STATEFP"].apply(lambda x: '{0:0>2}'.format(x))

<ipython-input-48-d0558d848624>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ML_NYC_PopandHHs["TRACTCE"] = df_ML_NYC_PopandHHs["TRACTCE"].apply(lambda x: '{0:0>6}'.format(x))
<ipython-input-48-d0558d848624>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ML_NYC_PopandHHs["COUNTYFP"] = df_ML_NYC_PopandHHs["COUNTYFP"].apply(lambda x: '{0:0>3}'.format(x))
<ipython-input-48-d0558d848624>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ML_NYC_PopandHHs["STATEFP"] = df_ML_NYC_PopandHHs["STATEFP"].apply(lambda x: '{0:0>2}'.format(x))

In [49]:
##df_ML_NYC_with_trees = pd.merge(df_ML_NYC, groupedTract_count, how = 'right', left_on = ['COUNTYFP','TRACTCE'], right_on = ['COUNTYFP','TRACTCE']) 
df_ML_NYC_withCrimesStats = pd.merge(df_ML_NYC, df_ML_NYC_PopandHHs, how = 'left', left_on = ['COUNTYFP','TRACTCE'], right_on = ['COUNTYFP','TRACTCE'])
print("shape of df_ML_NYC_withCrimesStats: ", df_ML_NYC_withCrimesStats.shape)
df_ML_NYC_withCrimesStats[1:5]

shape of df_ML_NYC_withCrimesStats:  (2140, 81)

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats_x,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,index,AFFGEOID,GEOID,State,County,Tract,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,crimeStats_y,STATEFP_y
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.377760,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1667,1400000US36005033000,36005033000,36,5,33000,5885,1433,2490,36
2,"Census Tract 358, Bronx County, New York",23.1,22.8,6.6,84.0,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,35.2,0.0,15.5,8.4,70.1,70.1,4.3,5.5,9.8,0.0,95.8,1.6,3.5,3.1,0.0,0.9,2.9,65.9,3.34,1.9,30.7,1.1,0.0,0.0,18.6,5.4,19.0,0.0,0.0,10.4,1667,low,141.872662,109.079761,105.321965,105.806697,115.169251,118.468611,188.010277,1496.191617,163.281225,115.063963,104.303041,005,035800,36,4048,1400000US36005035800,36005035800,36,5,35800,8054,1885,1667,36
3,"Census Tract 371, Bronx County, New York",20.2,48.9,3.8,54.0,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,33.0,7.5,53.6,1.4,40.8,40.8,6.2,24.2,0.0,29.4,95.1,0.0,1.5,63.2,0.0,1.8,19.9,10.4,4.02,3.5,41.1,0.0,5.5,0.0,30.9,6.2,20.5,1.1,0.0,27.3,2504,high,96.560279,88.540912,124.649755,70.359553,94.073286,65.815895,100.891534,1496.191617,116.228428,86.561881,104.873003,005,037100,36,4049,1400000US36005037100,36005037100,36,5,37100,4322,888,2504,36
4,"Census Tract 385, Bronx County, New York",38.9,38.6,4.0,49.0,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,18.9,9.7,60.5,0.4,21.8,21.8,16.8,44.6,55.0,59.5,91.5,52.7,4.0,72.9,0.0,4.4,12.7,1.6,2.19,2.9,26.7,26.9,0.0,0.0,0.0,12.4,12.2,0.2,0.0,8.3,3443,high,57.188096,62.847123,59.794228,73.704818,112.430046,85.602057,111.046050,1496.191617,111.884065,98.525718,106.867870,005,038500,36,2429,1400000US36005038500,36005038500,36,5,38500,4757,1028,3443,36

In [50]:
df_ML_NYC_withCrimesStats[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats_x,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,index,AFFGEOID,GEOID,State,County,Tract,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,crimeStats_y,STATEFP_y
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1667,1400000US36005033000,36005033000,36,5,33000,5885,1433,2490,36

In [51]:
##df_ML_NYC_with_trees.drop('STATEFP_y', inplace = True, axis=1) remove crimeStats_y
##  rename crimeStats_x to crimeStats #df2 = df.rename({'a': 'X', 'b': 'Y'}, axis=1) 
##df_ML_NYC_with_trees.rename(columns = {'STATEFP_x':'STATEFP'},inplace = True) 

df_ML_NYC_withCrimesStats.drop('crimeStats_y', inplace = True, axis=1) ## remove crimeStats_y
df_ML_NYC_withCrimesStats.rename(columns = {'crimeStats_x':'crimeStats'},inplace = True) ## rename crimeStats

In [52]:
df_ML_NYC_withCrimesStats["TRACTCE"][1:3]

1    033000
2    035800
Name: TRACTCE, dtype: object

In [53]:
df_ML_NYC_withCrimesStats["COUNTYFP"][1:3]

1    005
2    005
Name: COUNTYFP, dtype: object

df_ML_NYC[1:5]

In [54]:
df_ML_NYC_withCrimesStats[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,index,AFFGEOID,GEOID,State,County,Tract,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,STATEFP_y
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1667,1400000US36005033000,36005033000,36,5,33000,5885,1433,36

In [108]:
##points_in_map = points_in_map.join(census_tract_df[['STATEFP','COUNTYFP','TRACTCE','ALAND']],on='index_right')
##df_ML_NYC_with_trees = df_ML_NYC.join(points_in_map_withTrees[['COUNTYFP','TRACTCE']],on=['COUNTYFP','TRACTCE'])
##dc_NYCAll = pd.merge(left = dc_NYC1, right = dc_NYC2, how = 'right', left_on = ['NAME','State','County','Tract'], right_on = ['NAME','State','County','Tract'])
df_ML_NYC_with_trees = pd.merge(df_ML_NYC_withCrimesStats, groupedTract_count, how = 'left', left_on = ['COUNTYFP','TRACTCE'], right_on = ['COUNTYFP','TRACTCE']) 
df_ML_NYC_with_trees[1:5]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,index,AFFGEOID,GEOID,State,County,Tract,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,STATEFP_y,ALAND,treesStats,trees
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.377760,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1667,1400000US36005033000,36005033000,36,5,33000,5885,1433,36,206129.0,198.0,low
2,"Census Tract 358, Bronx County, New York",23.1,22.8,6.6,84.0,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,35.2,0.0,15.5,8.4,70.1,70.1,4.3,5.5,9.8,0.0,95.8,1.6,3.5,3.1,0.0,0.9,2.9,65.9,3.34,1.9,30.7,1.1,0.0,0.0,18.6,5.4,19.0,0.0,0.0,10.4,1667,low,141.872662,109.079761,105.321965,105.806697,115.169251,118.468611,188.010277,1496.191617,163.281225,115.063963,104.303041,005,035800,36,4048,1400000US36005035800,36005035800,36,5,35800,8054,1885,36,651471.0,596.0,high
3,"Census Tract 371, Bronx County, New York",20.2,48.9,3.8,54.0,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,33.0,7.5,53.6,1.4,40.8,40.8,6.2,24.2,0.0,29.4,95.1,0.0,1.5,63.2,0.0,1.8,19.9,10.4,4.02,3.5,41.1,0.0,5.5,0.0,30.9,6.2,20.5,1.1,0.0,27.3,2504,high,96.560279,88.540912,124.649755,70.359553,94.073286,65.815895,100.891534,1496.191617,116.228428,86.561881,104.873003,005,037100,36,4049,1400000US36005037100,36005037100,36,5,37100,4322,888,36,198178.0,323.0,high
4,"Census Tract 385, Bronx County, New York",38.9,38.6,4.0,49.0,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,18.9,9.7,60.5,0.4,21.8,21.8,16.8,44.6,55.0,59.5,91.5,52.7,4.0,72.9,0.0,4.4,12.7,1.6,2.19,2.9,26.7,26.9,0.0,0.0,0.0,12.4,12.2,0.2,0.0,8.3,3443,high,57.188096,62.847123,59.794228,73.704818,112.430046,85.602057,111.046050,1496.191617,111.884065,98.525718,106.867870,005,038500,36,2429,1400000US36005038500,36005038500,36,5,38500,4757,1028,36,189195.0,310.0,low

In [109]:
df_ML_NYC_with_trees.shape

(2140, 83)

In [110]:
## All_CSVs_11.drop('Popo_Density_Per_Hector', inplace = True, axis=1)  ,'index','State','County','Tract'

df_ML_NYC_with_trees.drop('STATEFP_y', inplace = True, axis=1)

In [111]:
df_ML_NYC_with_trees.drop('index', inplace = True, axis=1)

In [112]:
df_ML_NYC_with_trees.drop('State', inplace = True, axis=1)

In [113]:
df_ML_NYC_with_trees.drop('County', inplace = True, axis=1)

In [114]:
df_ML_NYC_with_trees.drop('Tract', inplace = True, axis=1)

In [105]:
#df2 = df.rename({'a': 'X', 'b': 'Y'}, axis=1) 
df_ML_NYC_with_trees.rename(columns = {'STATEFP_x':'STATEFP'},inplace = True) 
df_ML_NYC_with_trees.rename(columns = {'ALAND_x':'ALAND_Hectors'},inplace = True) 
df_ML_NYC_with_trees.rename(columns = {'ALAND_y':'ALAND'},inplace = True) 
df_ML_NYC_with_trees[200:201]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees
200,"Census Tract 241, Bronx County, New York",33.0,24.4,6.0,18.0,15.9,15.2,14.7,5.5,93.6,0.5,52.5,76.7,0.6,8.9,19.3,39.7,14.8,8.8,9.9,0.0,8.8,17.9,6.1,1.5,19.6,10.1,46.9,2.0,33.8,33.8,7.3,27.4,8.7,56.5,92.4,0.0,1.7,80.9,0.0,0.4,8.1,3.3,4.98,1.0,30.7,0.0,0.0,0.0,41.5,8.8,9.2,0.0,0.0,10.8,5767,high,80.295818,80.823673,69.392252,67.498337,121.751519,93.715212,154.885546,1496.191617,130.865591,115.767718,107.437832,005,024100,36,1400000US36005024100,36005024100,6635,1480,134661,229,low

In [115]:
df_ML_NYC_with_trees.shape

(2140, 78)

In [118]:
## Trees went down from 2140 to 1644 when I ran the .dropna () so not doing it after all. 
##df_ML_NYC_with_trees = df_ML_NYC_with_trees.dropna() ## 2136 to 2123 so removed 13 NaN rows. 

df_ML_NYC_with_trees = df_ML_NYC_with_trees[df_ML_NYC_with_trees['treesStats'].notna()]

In [119]:
print("shape file", df_ML_NYC_with_trees.shape)
df_ML_NYC_with_trees[1:3]

shape file (2127, 78)

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.377760,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1400000US36005033000,36005033000,5885,1433,206129.0,198.0,low
2,"Census Tract 358, Bronx County, New York",23.1,22.8,6.6,84.0,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,35.2,0.0,15.5,8.4,70.1,70.1,4.3,5.5,9.8,0.0,95.8,1.6,3.5,3.1,0.0,0.9,2.9,65.9,3.34,1.9,30.7,1.1,0.0,0.0,18.6,5.4,19.0,0.0,0.0,10.4,1667,low,141.872662,109.079761,105.321965,105.806697,115.169251,118.468611,188.010277,1496.191617,163.281225,115.063963,104.303041,005,035800,36,1400000US36005035800,36005035800,8054,1885,651471.0,596.0,high

In [120]:
url_NewYorkNTAs = 'https://raw.githubusercontent.com/maireadmanifold/files/main/2010_Census_Tract_to_NTA_Tim_Nov3rd.csv'
df_NewYorkNTAs = pd.read_csv(url_NewYorkNTAs, error_bad_lines=False, index_col=0)
df_NewYorkNTAs

,2010 Census COUNTYFP,2010 Census Tract,NTA,NTA Name
Borough,,,,
Brooklyn,47,100,BK09,Brooklyn Heights-Cobble Hill
Brooklyn,47,301,BK09,Brooklyn Heights-Cobble Hill
Brooklyn,47,501,BK09,Brooklyn Heights-Cobble Hill
Brooklyn,47,502,BK09,Brooklyn Heights-Cobble Hill
Brooklyn,47,700,BK09,Brooklyn Heights-Cobble Hill
...,...,...,...,...
Staten Island,85,14608,SI54,Great Kills
Staten Island,85,15601,SI54,Great Kills
Staten Island,85,15603,SI54,Great Kills
Staten Island,85,15400,SI99,park-cemetery-etc-Staten Island
Staten Island,85,990100,SI99,park-cemetery-etc-Staten Island

In [121]:
##df_ML_NYC_with_trees.rename(columns = {'ALAND_y':'ALAND'},inplace = True) 
df_NewYorkNTAs.rename(columns = {'2010 Census Tract':'TRACTCE'},inplace = True) 
df_NewYorkNTAs.rename(columns = {'2010 Census COUNTYFP':'COUNTYFP'},inplace = True) 
df_NewYorkNTAs["TRACTCE"] = df_NewYorkNTAs["TRACTCE"].apply(lambda x: '{0:0>6}'.format(x))
df_NewYorkNTAs["COUNTYFP"] = df_NewYorkNTAs["COUNTYFP"].apply(lambda x: '{0:0>3}'.format(x))
df_NewYorkNTAs

              COUNTYFP TRACTCE   NTA                         NTA Name
Borough
Brooklyn           047  000100  BK09     Brooklyn Heights-Cobble Hill
Brooklyn           047  000301  BK09     Brooklyn Heights-Cobble Hill
Brooklyn           047  000501  BK09     Brooklyn Heights-Cobble Hill
Brooklyn           047  000502  BK09     Brooklyn Heights-Cobble Hill
Brooklyn           047  000700  BK09     Brooklyn Heights-Cobble Hill
...                ...     ...   ...                              ...
Staten Island      085  014608  SI54                      Great Kills
Staten Island      085  015601  SI54                      Great Kills
Staten Island      085  015603  SI54                      Great Kills
Staten Island      085  015400  SI99  park-cemetery-etc-Staten Island
Staten Island      085  990100  SI99  park-cemetery-etc-Staten Island

[2168 rows x 4 columns]

In [122]:
##df_ML_NYC_with_trees = pd.merge(df_ML_NYC, groupedTract_count, how = 'right', left_on = ['COUNTYFP','TRACTCE'], right_on = ['COUNTYFP','TRACTCE']) 
df_ML_NYC_with_treesCrime_withNTAs = pd.merge(df_ML_NYC_with_trees, df_NewYorkNTAs, how = 'left', left_on = ['COUNTYFP','TRACTCE'], right_on = ['COUNTYFP','TRACTCE'])

In [123]:
df_ML_NYC_with_treesCrime_withNTAs[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees,NTA,NTA Name
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1400000US36005033000,36005033000,5885,1433,206129.0,198.0,low,BX07,Bronxdale

In [136]:
print("no of rows in df_ML_NYC_with_treesCrime_withNTAs: ", df_ML_NYC_with_treesCrime_withNTAs.shape)

no of rows in df_ML_NYC_with_treesCrime_withNTAs:  (2127, 80)

In [140]:
#df['your column name'].isnull().sum()
df_ML_NYC_with_treesCrime_withNTAs['NTA'].isnull().sum()

10

In [141]:
## remove any NTAs that are NaNs df_ML_NYC_with_trees = df_ML_NYC_with_trees.dropna() ## 2123 to 2115 so removed 8 NaN rows
df_ML_NYC_with_treesCrime_withNTAsNoNaNs = df_ML_NYC_with_treesCrime_withNTAs
df_ML_NYC_with_treesCrime_withNTAsNoNaNs[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees,NTA,NTA Name
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1400000US36005033000,36005033000,5885,1433,206129.0,198.0,low,BX07,Bronxdale

In [142]:
## find total trees for NTA areas
groupedTreesPerNTA = df_ML_NYC_with_treesCrime_withNTAsNoNaNs.groupby(["NTA Name"])["treesStats"].sum().sort_values(ascending=False).reset_index(name ='TotalNTATrees')
groupedTreesPerNTA[1:20]

                                          NTA Name  TotalNTATrees
1                                      Great Kills        10723.0
2                            Bayside-Bayside Hills         9819.0
3                                    East New York         9583.0
4                                Rossville-Woodrow         9247.0
5                New Springville-Bloomfield-Travis         8387.0
6           Charleston-Richmond Valley-Tottenville         8184.0
7                                     Forest Hills         7630.0
8                                       Whitestone         7624.0
9                                 South Ozone Park         7305.0
10            Douglas Manor-Douglaston-Little Neck         7213.0
11                                      St. Albans         7207.0
12  Georgetown-Marine Park-Bergen Beach-Mill Basin         7195.0
13                                     Murray Hill         7112.0
14                                   Arden Heights         6977.0
15                                       Bay Ridge         6901.0
16                                  Queens Village         6862.0
17                                 Jackson Heights         6828.0
18             Glen Oaks-Floral Park-New Hyde Park         6709.0
19                                       Ridgewood         6440.0

In [143]:
## find total crimes for NTA areas
groupedCrimesPerNTA = df_ML_NYC_with_treesCrime_withNTAsNoNaNs.groupby(["NTA Name"])["crimeStats"].sum().sort_values(ascending=False).reset_index(name ='TotalNTACrimes')
groupedCrimesPerNTA[1:200]

                                              NTA Name  TotalNTACrimes
1                                        East New York          124003
2                               Mott Haven-Port Morris          119410
3                                    East Harlem North          117635
4                                Midtown-Midtown South          114134
5                                          Brownsville          112917
6                    Central Harlem North-Polo Grounds          102204
7                                      Jackson Heights           97509
8                                              Bedford           96650
9          Hudson Yards-Chelsea-Flat Iron-Union Square           92930
10                            Washington Heights South           85541
11                            Washington Heights North           79256
12                                   East Harlem South           77195
13                                           Chinatown           72176
14                                         Hunts Point           71828
15                         park-cemetery-etc-Manhattan           69344
16                                             Jamaica           69025
17                               North Side-South Side           67687
18                      Melrose South-Mott Haven North           66081
19                                        North Corona           63500
20                                      Bushwick South           61743
21                                  Stuyvesant Heights           60861
22                                        West Village           59318
23                                Central Harlem South           58280
24                                      West Concourse           56113
25                                      Bushwick North           54697
26                            Williamsbridge-Olinville           54471
27                                            Flatbush           51938
28                                             Clinton           51900
29                                    Hamilton Heights           51776
30                                          Mount Hope           48890
31                                     Upper West Side           46979
32                                             Astoria           44867
33                    East Concourse-Concourse Village           44116
34                                     Lower East Side           43789
35                                  Morrisania-Melrose           42530
36                                    Sunset Park West           42303
37              SoHo-TriBeCa-Civic Center-Little Italy           41644
38                          Bedford Park-Fordham North           41396
39                                            Flushing           39417
40                                            Elmhurst           38758
41                                       Richmond Hill           37613
42                   Prospect Lefferts Gardens-Wingate           37446
43                              Far Rockaway-Bayswater           37122
44                                             Norwood           36798
45                                           Ridgewood           36378
46            Schuylerville-Throgs Neck-Edgewater Park           36184
47     Soundview-Castle Hill-Clason Point-Harding Park           35924
48                                  Claremont-Bathgate           35085
49                                        East Tremont           34926
50           West New Brighton-New Brighton-St. George           34745
51                    East New York (Pennsylvania Ave)           34671
52    DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill           34650
53            Carroll Gardens-Columbia Street-Red Hook           34638
54                                  Marble Hill-Inwood           34600
55                                             Erasmus           32494
56                                 Kingsbridge Heights           32353
57                                   East Williamsburg           32015
58                                          Ocean Hill           31628
59                                      Manhattanville           31585
60                                       West Brighton           31334
61                                            Longwood           30650
62                                        East Village           30491
63                                      Queens Village           30076
64                                    South Ozone Park           29951
65                            Hammels-Arverne-Edgemere           29896
66                       Upper East Side-Carnegie Hill           28957
67                             Cypress Hills-City Line           28605
68                                       Fordham South           27661
69                                        Clinton Hill           27572
70                   University Heights-Morris Heights           27350
71                                          Greenpoint           27180
72                                Rugby-Remsen Village           26914
73                                        Baisley Park           25862
74                                    Sunset Park East           24723
75                Hunters Point-Sunnyside-West Maspeth           24601
76                             Turtle Bay-East Midtown           24554
77                                 Crown Heights South           23948
78                                            Canarsie           23920
79                                  Stapleton-Rosebank           23870
80                                    Prospect Heights           23680
81                                           Bay Ridge           23513
82                                         Fort Greene           23463
83                                          Highbridge           22735
84                                  Soundview-Bruckner           22693
85                                             Belmont           22448
86                                Seagate-Coney Island           21734
87                                           Flatlands           21046
88      Sheepshead Bay-Gerritsen Beach-Manhattan Beach           20426
89                              West Farms-Bronx River           20067
90                                 Morningside Heights           19742
91                              East Flatbush-Farragut           19725
92                                          St. Albans           19711
93                                       South Jamaica           19489
94                                   Crotona Park East           19442
95                                Murray Hill-Kips Bay           19435
96                               Van Cortlandt Village           19365
97                     Eastchester-Edenwald-Baychester           18920
98                             Briarwood-Jamaica Hills           18788
99                                            Gramercy           18618
100                                 Woodlawn-Wakefield           18528
101                          Springfield Gardens North           16980
102                                     Pelham Parkway           16564
103                                          Yorkville           16551
104           Queensbridge-Ravenswood-Long Island City           16504
105                                       Borough Park           16014
106                                           Woodside           15910
107                                   Bensonhurst West           15689
108                            park-cemetery-etc-Bronx           15567
109                             New Dorp-Midland Beach           15447
110                                          Bronxdale           15377
111  Mariner's Harbor-Arlington-Port Ivory-Granitev...           14956
112                                 Park Slope-Gowanus           14914
113                                       Forest Hills           14875
114                                      Port Richmond           14631
115                 Pomonok-Flushing Heights-Hillcrest           14630
116                        Lenox Hill-Roosevelt Island           14470
117                                     Lincoln Square           14404
118            Van Nest-Morris Park-Westchester Square           13294
119                              Bayside-Bayside Hills           13158
120                                          Homecrest           13035
121                         Spuyten Duyvil-Kingsbridge           11538
122                  Battery Park City-Lower Manhattan           10886
123                                             Corona           10831
124  Breezy Point-Belle Harbor-Rockaway Park-Broad ...           10616
125                                        Old Astoria            9797
126                                          Woodhaven            9599
127                                           Steinway            9556
128                                          Laurelton            9527
129                                         Co-op City            9339
130                                   Bensonhurst East            8953
131                                         Bath Beach            8665
132                                          Gravesend            8569
133                                          Bellerose            8411
134               Springfield Gardens South-Brookville            8296
135                                     Brighton Beach            8198
136                                           Rosedale            8148
137                                       Williamsburg            7922
138                                            Madison            7606
139                                        Murray Hill            7327
140                  New Springville-Bloomfield-Travis            7327
141             Charleston-Richmond Valley-Tottenville            7323
142     Georgetown-Marine Park-Bergen Beach-Mill Basin            6888
143                                            Midwood            6857
144                         Jamaica Estates-Holliswood            6529
145                                    Cambria Heights            6408
146                                         Ozone Park            6345
147                              Westchester-Unionport            6075
148                                      East Elmhurst            5991
149                                          Rego Park            5926
150                Pelham Bay-Country Club-City Island            5842
151                            Allerton-Pelham Gardens            5706
152                                      Dyker Heights            5654
153                      Grymes Hill-Clifton-Fox Hills            5595
154                                             Hollis            5194
155  Todt Hill-Emerson Hill-Heartland Village-Light...            5184
156                                  Kew Gardens Hills            4967
157                                        Parkchester            4919
158                           New Brighton-Silver Lake            4865
159         Annadale-Huguenot-Prince's Bay-Eltingville            4740
160                           Kensington-Ocean Parkway            4650
161                                   Elmhurst-Maspeth            4502
162                                            Maspeth            4471
163                                           Glendale            4413
164                                        Great Kills            4387
165                  Old Town-Dongan Hills-South Beach            3937
166                            Lindenwood-Howard Beach            3547
167                                        Kew Gardens            3315
168                    Grasmere-Arrochar-Ft. Wadsworth            3287
169                               Fresh Meadows-Utopia            3260
170                                     Middle Village            3199
171                                        Westerleigh            3061
172                Glen Oaks-Floral Park-New Hyde Park            2998
173                                      College Point            2848
174                           park-cemetery-etc-Queens            2830
175                                  Rossville-Woodrow            2652
176                                Ocean Parkway South            2528
177                       Brooklyn Heights-Cobble Hill            2513
178                                    Oakland Gardens            2479
179                North Riverdale-Fieldston-Riverdale            2477
180                                    Queensboro Hill            2219
181                                         Whitestone            1922
182                                      Arden Heights            1878
183                              Oakwood-Oakwood Beach            1834
184                         park-cemetery-etc-Brooklyn            1766
185               Douglas Manor-Douglaston-Little Neck            1694
186                                      East Flushing            1654
187                                      Starrett City            1479
188                                         Auburndale            1401
189                   Ft. Totten-Bay Terrace-Clearview            1349
190                                    Windsor Terrace            1282
191                     Stuyvesant Town-Cooper Village            1057

In [144]:
df_ML_NYC_withTotalTreesPerNTA = pd.merge(df_ML_NYC_with_treesCrime_withNTAsNoNaNs, groupedTreesPerNTA, how = 'left', left_on = ['NTA Name'], right_on = ['NTA Name'])  
df_ML_NYC_withTotalTreesPerNTA[1:40]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees,NTA,NTA Name,TotalNTATrees
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.377760,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1400000US36005033000,36005033000,5885,1433,206129.0,198.0,low,BX07,Bronxdale,1503.0
2,"Census Tract 358, Bronx County, New York",23.1,22.8,6.6,84.0,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,35.2,0.0,15.5,8.4,70.1,70.1,4.3,5.5,9.8,0.0,95.8,1.6,3.5,3.1,0.0,0.9,2.9,65.9,3.34,1.9,30.7,1.1,0.0,0.0,18.6,5.4,19.0,0.0,0.0,10.4,1667,low,141.872662,109.079761,105.321965,105.806697,115.169251,118.468611,188.010277,1496.191617,163.281225,115.063963,104.303041,005,035800,36,1400000US36005035800,36005035800,8054,1885,651471.0,596.0,high,BX03,Eastchester-Edenwald-Baychester,2639.0
3,"Census Tract 371, Bronx County, New York",20.2,48.9,3.8,54.0,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,33.0,7.5,53.6,1.4,40.8,40.8,6.2,24.2,0.0,29.4,95.1,0.0,1.5,63.2,0.0,1.8,19.9,10.4,4.02,3.5,41.1,0.0,5.5,0.0,30.9,6.2,20.5,1.1,0.0,27.3,2504,high,96.560279,88.540912,124.649755,70.359553,94.073286,65.815895,100.891534,1496.191617,116.228428,86.561881,104.873003,005,037100,36,1400000US36005037100,36005037100,4322,888,198178.0,323.0,high,BX17,East Tremont,2366.0
4,"Census Tract 385, Bronx County, New York",38.9,38.6,4.0,49.0,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,18.9,9.7,60.5,0.4,21.8,21.8,16.8,44.6,55.0,59.5,91.5,52.7,4.0,72.9,0.0,4.4,12.7,1.6,2.19,2.9,26.7,26.9,0.0,0.0,0.0,12.4,12.2,0.2,0.0,8.3,3443,high,57.188096,62.847123,59.794228,73.704818,112.430046,85.602057,111.046050,1496.191617,111.884065,98.525718,106.867870,005,038500,36,1400000US36005038500,36005038500,4757,1028,189195.0,310.0,low,BX01,Claremont-Bathgate,1658.0
5,"Census Tract 421, Bronx County, New York",24.9,40.3,6.5,0.0,0.0,0.0,15.4,3.9,90.0,0.0,52.0,70.8,0.2,14.0,36.0,31.7,16.5,5.3,4.7,0.0,13.4,9.4,4.5,2.1,21.0,12.2,42.9,3.4,43.2,43.2,12.7,29.6,0.0,54.2,93.4,0.0,3.2,93.4,0.0,7.8,13.3,4.3,2.85,5.5,26.9,24.7,0.0,52.7,0.0,10.5,10.4,3.7,3.9,37.5,3649,high,85.592314,79.276179,77.497995,80.656382,NaN,98.102938,134.529827,1496.191617,143.631335,93.247554,99.173383,005,042100,36,1400000US36005042100,36005042100,5763,1283,246182.0,296.0,low,BX43,Norwood,1801.0
6,"Census Tract 451.01, Bronx County, New York",11.7,51.7,7.8,36.0,0.0,0.0,2.6,8.2,91.1,1.2,77.1,21.5,51.4,3.1,56.0,9.1,1.1,6.2,14.4,0.7,2.8,6.6,20.8,8.9,32.4,0.8,2.9,10.2,83.1,83.1,6.6,1.6,0.0,20.7,89.5,0.0,8.4,53.2,0.0,4.6,3.7,32.1,2.42,2.7,20.4,0.0,4.1,7.4,32.2,7.5,22.5,0.0,3.0,86.1,1036,low,157.124696,201.912524,160.351913,169.797573,65.168543,122.194039,36.042695,1496.191617,50.394615,72.134901,80.934600,005,045101,36,1400000US36005045101,36005045101,1544,364,176003.0,189.0,low,BX62,Woodlawn-Wakefield,3928.0
7,"Census Tract 118, Bronx County, New York",13.0,37.6,5.4,10.0,0.0,0.0,5.3,12.8,89.5,0.1,84.8,27.5,24.4,5.5,39.3,13.7,8.2,10.8,8.0,0.0,3.9,4.7,15.9,10.5,38.2,1.4,2.9,16.8,84.1,84.1,4.1,7.6,0.0,0.0,97.3,0.6,0.0,0.0,0.0,1.8,0.0,69.4,2.48,1.6,15.5,0.4,0.9,0.8,26.9,6.3,18.5,0.5,0.8,75.7,868,low,169.784728,122.619488,152.773138,136.428549,101.514111,145.208906,126.056058,1496.191617,107.272356,87.617513,90.338973,005,011800,36,1400000US36005011800,36005011800,5400,1002,989676.0,384.0,high,BX52,Schuylerville-Throgs Neck-Edgewater Park,4848.0
8,"Census Tract 204, Bronx County, New York",25.4,34.0,6.7,0.0,8.2,0.0,8.9,7.5,83.0,4.2,52.6,69.5,0.1,9.7,20.1,27.3,9.9,12.7,4.4,0.0,8.1,7.6,12.1,0.8,27.0,3.5,20.8,1.2,52.1,52.1,9.3,12.8,58.1,37.3,94.9,0.0,0.0,19.7,0.0,3.5,6.5,24.2,3.34,2.6,22.1,0.0,2.8,0.0,38.5,6.0,15.0,1.4,0.0,25.5,446,low,97.227419,94.339799,75.291911,89.660722,118.930547,111.100543,72.155422,1496.191617,69.710322,103.100126,103.448098,005,020400,36,1400000US36005020400,36005020400,3091,688,134282.0,263.0,low,BX59,Westchester-Unionport,2817.0
9,"Census Tract 248, Bronx County, New York",12.0,35.1,4.8,0.0,0.0,0.0,5.7,7.2,86.1,2.5,58.1,50.5,1.1,9.7,31.2,32.7,10.0,2.5,8.8,0.0,5.6,5.5,5.4,3.1,26.4,0.8,15.2,3.6,63.6,63.6,11.3,12.0,0.0,25.8,92.5,0.0,2.9,38.5,1.1,3.0,5.7,26.5,3.08,3.0,23.2,0.0,0.0,3.1,38.7,2.9,28.7,0.4,0.3,60.1,174,low,126.779992,126.044877,120.596883,139.023664,122.650960,117.061227,71.268360,1496.191617,73.519995,87.265636,88.344106,005,024800,36,1400000US36005024800,36005024800,3053,714,277912.0,347.0,high,BX49,Pelham Parkway,2309.0
10,"Census Tract 408, Bronx County, New York",34.8,31.8,5.2,40.0,0.0,7.1,12.3,12.0,87.1,1.4,47.5,33.9,0.4,19.2,11.4,40.7,10.7,8.3,8.3,0.0,16.1,16.1,7.2,0.9,20.4,8.1,33.0,0.0,45.7,45.7,15.4,31.0,42.7,53.1,95.3,0.0,2.2,56.2,0.9,12.1,8.6,16.1,3.87,3.9,23.6,0.0,0.0,0.0,45.0,10.6,9.8,0.0,0.0,16.5,4390,high,76.777320,88.274568,82.913800,101.239902,126.044303,108.120200,107.264368,1496.191617,107.673374,100.285106,99.743345,005,040800,36,1400000US36005040800,36005040800,4595,1098,124014.0,156.0,low,BX44,Williamsbridge-Olinville,3242.0
11,"Census Tract 484, Bronx County, New York",28.8,31.3,8.1,18.0,0.0,15.2,9.0,11.2,90.7,3.9,48.4,21.1,1.0,8.9,25.4,28.8,16.7,2.9,4.5,0.0,3.6,6.3,13.2,4.9,27.0,0.9,13.6,4.7,67.9,67.9,9.2,1.3,0.0,0.0,93.9,2.2,0.0,0.0,1.2,4.3,3.4,57.1,3.33,5.4,35.6,0.0,0.0,1.8,35.4,3.3,12.5,0.0,0.0,6.9,2932,high,138.465094,119.939188,111.729430,121.012450,127.393464,111.597266,96.316166,1496.191617,83.278103,115.415841,112.282509,005,048400,36,1400000US36005048400,36005048400,4126,856,697175.0,447.0,high,BX03,Eastchester-Edenwald-Baychester,2639.0
12,"Census Tract 247, Bronx County, New York",26.4,40.1,10.9,0.0,27.5,0.0,15.3,11.9,92.5,0.4,51.6,57.1,0.3,6.4,30.0,32.9,8.3,5.7,2.9,0.0,12.2,7.2,15.5,0.0,16.3,4.8,27.0,0.0,48.9,48.9,8.9,24.7,19.5,56.3,98.1,0.0,0.0,88.1,0.0,1.7,11.4,4.9,2.32,6.5,21.7,0.0,39.5,0.0,0.0,5.7,10.2,0.3,0.0,5.3,474,low,85.048603,107.279409,102.438006,99.693984,NaN,110.438244,47.551146,1496.191617,51.397160,93.247554,93.188783,005,024700,36,1400000US36005024700,36005024700,2037,461,145941.0,71.0,low,BX36,University Heights-Morris Heights,2045.0
13,"Census Tract 266.02, Bronx County, New York",23.4,45.5,7.7,96.0,0.0,40.0,14.4,8.1,85.4,0.0,69.8,58.5,7.9,9.5,38.4,28.8,5.6,7.8,9.6,0.0,8.8,6.7,22.5,0.6,33.8,2.3,16.2,1.1,76.1,76.1,1.9,21.5,13.7,31.5,92.8,0.0,3.8,47.2,0.0,7.8,8.8,24.0,2.52,6.4,17.9,6.7,14.7,0.0,19.7,4.0,23.2,0.7,0.6,61.2,849,low,107.162646,153.326617,140.295947,129.745620,44.767600,105.471007,121.550722,1496.191617,162.546025,75.301799,79.509695,005,026602,36,1400000US36005026602,36005026602,5207,1325,303397.0,410.0,high,BX10,Pelham Bay-Country Club-City Island,3113.0
14,"Census Tract 364, Bronx County, New York",21.2,26.8,3.1,2.0,0.0,35.4,9.7,9.8,93.5,0.5,52.9,20.2,0.0,5.1,26.6,34.2,11.8,4.9,6.2,0.0,4.6,7.5,12.7,6.0,34.5,0.8,21.8,8.2,71.4,71.4,7.0,0.8,0.0,0.0,88.0,1.9,3.4,0.5,0.0,0.0,2.2,61.1,3.27,1.8,28.0,0.0,0.0,0.0,19.1,3.8,19.5,0.7,0.0,1.8,1877,low,125.114486,120.744964,95.654477,104.947572,110.876468,111.928415,62.747905,1496.191617,55.607851,113.304575,110.857604,005,036400,36,1400000US36005036400,36005036400,2688,609,203683.0,220.0,low,BX03,Eastchester-Edenwald-Baychester,2639.0
15,"Census Tract 449.02, Bronx County, New York",16.4,46.8,8.0,0.0,0.0,0.0,7.5,4.2,87.1,2.4,65.6,18.1,49.3,5.9,49.9,20.7,8.5,6.0,12.1,0.0,7.9,10.1,17.8,8.8,26.9,4.8,7.3,11.9,76.1,76.1,8.2,6.2,18.5,28.3,92.7,0.0,3.3,24.0,0.0,0.8,0.0,39.0,2.49,3.8,29.5,5.6,10.0,1.9,49.4,6.1,17.2,0.0,0.3,82.7,520,low,145.752072,150.872204,187.062061,111.640637,123.427749,104.394772,43.792808,1496.191617,54.872651,79.524329,86.349239,005,044902,36,1400000US36005044902,36005044902,1876,437,156698.0,230.0,low,BX62,Woodlawn-Wakefield,3928.0
16,"Census Tract 223, Bronx County, New York",41.5,29.9,5.9,11.0,12.0,12.7,17.1,4.7,95.4,2.4,47.7,80.6,0.2,11.1,20.7,46.6,16.1,6.3,7.2,0.0,15.0,23.0,6.2,0.0,30.0,9.5,45.7,0.0,24.6,24.6,10.4,37.0,73.9,52.2,97.9,NaN,1.0,90.6,0.0,1.0,6.9,0.0,NaN,1.3,34.4,NaN,NaN,NaN,NaN,3.5,12.7,5.0,1.9,25.1,6650,high,57.855236,56.940350,70.779139,61.246238,NaN,92.887339,118.539382,1496.191617,123.313082,96.766330,93.188783,005,022300,36,1400000US36005022300,36005022300,5078,1293,92765.0,158.0,low,BX63,West Concourse,2137.0
17,"Census Tract 254, Bronx County, New York",18.0,36.8,4.4,15.0,0.0,12.0,6.9,8.2,92.2,0.8,72.9,40.8,5.2,7.3,34.6,27.3,1.6,4.3,11.5,0.0,8.5,13.0,9.5,2.7,32.9,7.8,11.3,3.0,59.6,59.6,6.1,10.0,0.0,20.9,93.0,0.0,0.0,6.0,0.0,3.1,3.6,48.1,2.95,1.4,26.9,0.0,0.0,3.5,38.2,6.5,19.4,2.2,0.0,74.3,297,low,119.958605,120.471877,127.382808,122.393639,98.202535,120.786655,48.951769,1496.191617,51.998687,93.951309,98.603421,005,025400,36,1400000US36005025400,36005025400,2097,492,169924.0,344.0,high,BX37,Van Nest-Morris Park-Westchester Square,3156.0
18,"Census Tract 296, Bronx County, New York",12.6,45.0,5.7,56.0,0.0,0.0,6.2,5.3,89.4,6.1,56.2,55.8,0.9,6.1,57.6,18.8,2.6,4.4,13.3,0.0,11.5,3.2,14.6,5.0,23.9,2.4,12.3,5.2,81.4,81.4,2.7,10.2,0.0,0.0,94.6,0.0,4.5,78.5,0.0,9.5,7.6,17.3,2.61,6.0,15.6,0.0,0.0,0.0,39.7,5.1,14.2,0.0,0.3,35.2,9629,high,126.975291,134.857836,123.614979,123.359204,85.692137,114.577609,37.163194,1496.191617,46.651779,77.061186,83.499429,005,029600,36,1400000US36005029600,36005029600,1592,384,723313.0,216.0,low,BX49,Pelham Parkway,2309.0
19,"Census Tract 376, Bronx County, New York",28.8,34.8,6.3,36.0,0.0,10.5,9.8,8.3,87.4,1.4,54.8,63.9,0.0,15.4,32.1,28.5,7.0,10.4,8.7,0.0,11.0,12.6,8.3,2.8,39.7,8.3,34.4,4.3,44.3,44.3,6.0,11.0,0.0,23.4,93.7,0.0,2.9,36.4,0.0,3.5,14.1,32.7,2.52,3.3,40.7,9.4,27.3,0.0,14.8,6.1,16.3,0.0,0.0,11.2,535,low,131.946810,113.911043,114.443321,103.660151,103.231224,111.762841,54.134074,1496.191617,52.399705,99.933228,100.883269,005,037600,36,1400000US36005037600,36005037600,2319,511,124765.0,102.0,low,BX44,Williamsbridge-Olinville,3242.0
20,"Census Tract 27.01, Bronx County, New York",44.0,38.0,3.9,75.0,12.5,31.6,23.5,7.1,91.3,0.6,65.1,66.6,0.6,7.5,16.6,34.1,15.3,5.4,7.7,0.0,27.0,22.1,4.5,0.0,20.8,17.2,60.4,0.0,24.8,24.8,10.9,50.5,100.0,68.4,97.2,NaN,0.0,79.7,0.0,2.7,4.9,0.0,NaN,2.0,34.3,NaN,NaN,NaN,NaN,7.0,10.0,0.2,0.0,8.7,4787,high,51.174464,70.018189,71.797147,67.318402,NaN,36.426407,66.949773,1496.191617,70.913377,95.006942,102.023193,005,002701,36,1400000US36005002701,36005002701,2868,658,82641.0,70.0,low,BX39,Mott Haven-Port Morris,2507.0
21,"Census Tract 65, Bronx County, New York",31.1,43.7,3.5,23.0,7.1,10.2,17.1,4.2,94.8,1.5,65.9,67.8,0.0,11.4,11.1,51.5,13.5,1.8,9.2,0.0,24.8,17.4,4.8,0.0,21.3,12.4,43.0,0.0,27.2,27.2,17.3,41.6,65.6,76.9,96.1,0.0,0.8,70.4,0.0,3.8,11.6,2.3,2.16,5.6,30.5,0.0,53.3,0.0,0.0,8.4,10.0,0.3,0.0,18.8,15212,high,60.450363,69.751844,76.032063,76.913232,NaN,84.360248,124.001812,1496.191617,130.197227,94.303187,108.577756,005,006500,36,1400000US36005006500,36005006500,5312,1097,261808.0,326.0,high,BX34,Melrose South-Mott Haven North,2149.0
22,"Census Tract 157, Bronx County, New York",38.4,39.4,12.8,66.0,0.0,0.0,15.7,7.2,91.5,0.7,54.9,67.7,0.1,12.4,17.6,33.7,22.9,4.1,3.9,0.0,13.7,15.3,7.7,3.4,17.4,9.0,45.3,0.0,50.6,50.6,8.9,33.8,64.1,48.5,94.6,0.0,0.7,47.0,15.1,2.9,6.9,11.1,3.45,5.5,33.3,11.3,0.0,4.2,38.7,6.9,10.5,0.3,0.0,14.0,2480,high,88.999883,81.315904,97.860561,58.767700,114.147160,86.843867,103.342624,1496.191617,101.323920,102.044493,100.313307,005,015700,36,1400000US36005015700,36005015700,4427,918,319009.0,238.0,low,BX75,Crotona Park East,1426.0
23,"Census Tract 67, Bronx County, New York",36.6,34.8,8.7,80.0,4.6,0.0,29.8,5.0,95.5,0.0,56.4,72.3,0.6,13.0,17.6,41.0,10.2,7.6,5.5,0.0,23.4,22.9,6.8,4.7,29.9,15.7,58.2,2.4,22.9,22.9,13.8,43.8,42.4,69.1,96.1,0.0,0.0,63.5,0.0,1.0,7.9,5.3,2.26,2.0,30.7,0.0,0.0,0.0,11.3,5.9,12.9,0.0,0.6,7.1,12396,high,165.131936,73.183976,64.057887,64.956442,NaN,67.471641,169.381993,1496.191617,156.129735,109.082045,108.577756,005,006700,36,1400000US36005006700,36005006700,7256,1524,212430.0,197.0,low,BX34,Melrose South-Mott Haven North,2149.0
24,"Census Tract 407.02, Bronx County, New York",30.8,40.5,8.7,89.0,21.2,6.3,16.5,9.7,82.6,0.2,51.4,78.4,0.9,10.1,18.3,35.0,12.9,6.5,7.6,0.5,12.5,12.7,10.2,1.7,26.7,5.5,44.6,2.8,38.9,38.9,12.4,27.0,19.1,63.0,95.0,19.7,2.8,74.5,2.1,2.9,15.5,4.8,3.44,5.8,29.2,0.0,25.4,18.3,21.4,12.2,16.0,1.7,1.3,25.8,3286,high,73.969708,83.820888,88.492487,64.662464,99.061092,99.261960,160.861537,1496.191617,175.378606,91.488167,94.613688,005,040702,36,1400000US36005040702,36005040702,6891,1561,182164.0,233.0,low,BX05,Bedford Park-Fordham North,1822.0
25,"Census Tract 380, Bronx County, New York",43.9,42.5,9.1,96.0,0.0,0.0,12.4,6.9,94.0,0.8,60.6,33.4,0.7,13.8,28.3,29.6,9.6,8.4,4.2,1.4,16.6,19.1,10.0,0.7,30.7,11.9,35.8,0.0,46.5,46.5,6.6,43.2,82.3,57.5,94.2,3.3,2.3,37.8,1.1,2.0,8.0,32.2,2.67,2.3,20.6,16.9,5.0,6.2,21.9,8.9,12.9,0.0,0.0,6.9,6361,high,80.408310,87.401364,116.397897,95.314727,75.920944,112.921863,125.542497,1496.191617,127.991627,98.525718,105.157984,005,038000,36,1400000US36005038000,36005038000,5378,1102,213585.0,155.0,low,BX44,Williamsbridge-Olinville,3242.0
26,"Census Tract 25, Bronx County, New York",29.3,33.3,4.3,36.0,20.7,14.7,20.2,3.4,93.0,0.3,54.3,73.9,0.4,8.3,17.3,41.4,13.3,5.9,6.2,0.4,22.1,15.3,5.3,0.0,26.4,7.9,54.2,0.0,26.3,26.3,18.0,37.8,36.4,63.4,93.2,22.6,1.5,58.6,0.0,3.0,15.5,4.7,2.82,3.5,32.0,9.9,0.0,0.0,47.3,9.5,12.4,0.2,0.1,16.4,6741,high,75.538346,76.949881,67.876018,79.313207,93.991519,68.713450,137.424447,1496.191617,130.130391,106.267024,109.432699,005,002500,36,1400000US36005002500,36005002500,5887,1298,127492.0,171.0,low,BX39,Mott Haven-Port Morris,2507.0
27,"Census Tract 61, Bronx County, New York",20.4,61.5,3.9,0.0,9.3,14.7,4.0,8.1,97.1,0.0,81.7,18.7,0.0,9.2,27.4,27.2,4.6,7.2,11.9,0.0,6.5,11.0,12.9,0.0,49.2,3.5,12.6,0.0,69.1,69.1,7.7,9.1,0.0,7.9,92.1,6.4,9.4,94.9,0.0,2.9,2.2,48.6,1.67,0.0,21.5,5.4,1.5,1.8,0.0,2.2,34.3,0.5,0.0,10.0,645,low,96.930565,158.457958,121.303501,136.142174,20.891547,93.963574,86.301713,1496.191617,143.230317,60.874818,77.229847,005,006100,36,1400000US36005006100,36005006100,3697,825,242362.0,56.0,low,BX14,East Concourse-Concourse Village,2444.0
28,"Census Tract 227.01, Bronx County, New York",28.8,42.2,6.8,47.0,0.0,0.0,16.3,9.1,93.4,0.4,51.9,71.5,0.0,11.4,16.2,44.2,12.1,7.3,10.3,0.0,13.4,16.8,9.8,0.5,24.1,7.9,46.3,0.8,32.6,32.6,8.7,30.1,13.4,59.9,97.8,0.0,1.0,86.6,0.0,4.1,5.3,2.7,2.33,1.4,30.2,0.0,45.1,13.7,21.6,6.7,13.1,1.1,0.0,13.6,1447,low,87.209386,81.828364,71.859425,81.885513,NaN,99.179173,121.247253,1496.191617,124.048282,94.303187,102.308174,005,022701,36,1400000US36005022701,36005022701,5194,1072,114009.0,189.0,low,BX41,Mount Hope,2004.0
29,"Census Tract 79, Bronx County, New York",43.9,32.2,3.4,170.0,8.9,21.7,20.5,6.6,95.5,0.0,55.6,69.4,0.1,12.8,15.1,39.9,14.5,8.0,9.5,0.0,21.5,9.3,6.0,1.9,24.4,11.0,62.7,0.0,20.2,20.2,8.6,44.4,29.6,61.9,95.7,0.0,2.3,71.6,1.5,0.8,7.7,1.1,4.31,3.3,32.4,0.0,0.0,0.0,0.0,12.3,10.2,0.4,0.0,9.4,9793,high,70.121546,76.454279,72.120515,67.713752,NaN,70.617558,164.666562,1496.191617,158.870025,102.748249,104.873003,005,007900,36,1400000US36005007900,36005007900,7054,1611,197930.0,297.0,low,BX34,Melrose South-Mott Haven North,2149.0
30,"Census Tract 167, Bronx County, New York",31.1,32.1,6.0,79.0,0.0,0.0,17.0,8.6,89.5,0.0,65.7,61.5,0.3,14.0,14.4,48.1,6.9,3.5,8.1,1.6,14.5,10.6,13.6,0.0,12.8,16.0,47.0,0.0,27.9,27.9,6.2,33.0,0.0,52.7,96.9,13.6,0.0,71.7,1.0,2.8,8.2,5.5,3.26,3.0,27.3,0.0,0.0,0.0,0.0,11.6,5.4,0.5,0.3,12.5,2741,high,70.240287,88.500455,91.021939,81.467355,99.429045,90.403720,84.620965,1496.191617,69.041959,109.785800,109.432699,005,016700,36,1400000US36005016700,36005016700,3625,701,205837.0,248.0,low,BX01,Claremont-Bathgate,1658.0
31,"Census Tract 224.01, Bronx County, New York",19.0,51.7,8.3,30.0,0.0,0.0,6.6,6.9,88.0,0.9,56.1,59.4,0.6,16.0,27.4,22.7,22.2,7.2,7.2,0.6,14.4,5.9,19.6,1.4,22.2,1.5,16.2,2.9,54.0,54.0,9.9,22.3,0.0,36.3,95.7,0.0,3.3,92.9,0.0,3.0,5.7,12.8,1.52,4.6,30.5,0.0,60.0,18.6,0.0,6.0,12.3,0.0,0.3,17.1,2230,low,113.221587,124.163610,134.736423,96.619888,54.211724,120.372719,61.557375,1496.191617,75.792431,81.635595,95.183650,005,022401,36,1400000US36005022401,36005022401,2637,548,85053.0,87.0,low,BX49,Pelham Parkway,2309.0
32,"Census Tract 28, Bronx County, New York",34.0,38.0,0.9,0.0,40.5,13.5,8.3,9.6,97.7,0.0,78.6,36.1,0.0,4.1,30.3,25.7,13.1,8.0,10.4,0.0,4.2,6.3,8.7,0.0,38.8,1.4,14.2,0.0,66.9,66.9,3.0,6.1,0.0,15.7,94.5,7.3,3.2,80.6,0.0,4.5,0.8,19.8,2.65,0.0,27.8,0.0,0.0,7.6,0.0,5.6,22.8,1.4,0.0,15.7,871,low,104.192546,112.461321,82.858708,108.125574,65.372962,84.856972,122.998032,1496.191617,154.325153,80.228084,86.349239,005,002800,36,1400000US36005002800,36005002800,5269,1431,414588.0,233.0,low,BX09,Soundview-Castle Hill-Clason Point-Harding Park,3698.0
33,"Census Tract 158, Bronx County, New York",16.0,47.5,3.5,0.0,0.0,0.0,9.9,9.5,83.0,0.0,73.7,48.8,5.5,6.3,30.7,20.7,16.0,6.9,6.7,0.0,8.1,17.1,9.0,0.0,49.5,1.1,7.2,0.0,68.2,68.2,3.8,4.5,0.0,11.1,83.6,4.9,11.4,22.5,0.0,1.8,17.5,42.2,2.22,1.3,22.8,0.0,2.5,0.0,36.9,7.2,31.3,0.0,0.0,47.2,318,low,100.164709,104.154078,116.498501,132.074635,96.076585,120.289932,25.257899,1496.191617,31.346252,80.931840,94.613688,005,015800,36,1400000US36005015800,36005015800,1082,246,162176.0,211.0,low,BX52,Schuylerville-Throgs Neck-Edgewater Park,4848.0
34,"Census Tract 218, Bronx County, New York",29.1,22.3,3.9,0.0,0.0,44.1,19.4,5.5,87.5,0.3,54.5,64.0,0.5,7.2,16.7,43.0,12.5,6.1,13.6,0.0,7.6,17.5,10.0,1.3,24.7,9.9,40.4,1.6,48.8,48.8,12.6,26.2,44.8,75.8,94.2,0.0,1.5,62.1,0.0,1.8,3.7,20.9,3.23,3.1,27.8,10.1,0.0,15.4,38.5,9.9,14.0,0.0,0.0,17.7,1548,low,87.118767,81.255218,110.052710,71.804099,98.938441,107.292327,163.802845,1496.191617,155.060353,105.563269,97.748479,005,021800,36,1400000US36005021800,36005021800,7017,1802,320629.0,350.0,high,BX08,West Farms-Bronx River,1642.0

In [130]:
## find total crimes per county/tract combination
groupedCrimesPerTract = df_ML_NYC_with_treesCrime_withNTAsNoNaNs.groupby(["COUNTYFP","TRACTCE"])["crimeStats"].sum().sort_values(ascending=False).reset_index(name ='TotalTractCrimes')
groupedCrimesPerTract[1:5]

  COUNTYFP TRACTCE  TotalTractCrimes
1      005  003900             36415
2      047  116400             30849
3      061  018200             27608
4      061  016600             27029

In [145]:
df_ML_NYC_withTotalTreesandCrimesPerNTA = pd.merge(df_ML_NYC_withTotalTreesPerNTA, groupedCrimesPerNTA, how = 'left', left_on = ['NTA Name'], right_on = ['NTA Name'])  
df_ML_NYC_withTotalTreesandCrimesPerNTA[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees,NTA,NTA Name,TotalNTATrees,TotalNTACrimes
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1400000US36005033000,36005033000,5885,1433,206129.0,198.0,low,BX07,Bronxdale,1503.0,15377.0

In [146]:
## find total crimes for county/tract areas - see 148 above - seems to be a duplicate
groupedCrimesPerTract = df_ML_NYC_with_treesCrime_withNTAsNoNaNs.groupby(["COUNTYFP","TRACTCE"])["crimeStats"].sum().sort_values(ascending=False).reset_index(name ='TotalTractCrimes')
groupedCrimesPerTract[1:5]

  COUNTYFP TRACTCE  TotalTractCrimes
1      061  027100             43952
2      005  003900             36415
3      061  011900             34795
4      047  092400             31360

In [147]:
df_ML_NYC_withTotalTreesandCrimesPerTract = pd.merge(df_ML_NYC_withTotalTreesandCrimesPerNTA, groupedCrimesPerTract, how = 'inner',  on = ['COUNTYFP', 'TRACTCE'])
df_ML_NYC_withTotalTreesandCrimesPerTract[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,COUNTYFP,TRACTCE,STATEFP_x,AFFGEOID,GEOID,DP05_0001E-T Popo,DP02_0002E-T Fam HHs,ALAND,treesStats,trees,NTA,NTA Name,TotalNTATrees,TotalNTACrimes,TotalTractCrimes
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36,1400000US36005033000,36005033000,5885,1433,206129.0,198.0,low,BX07,Bronxdale,1503.0,15377.0,2490

In [148]:
df_ML_NYC_withTotalTreesandCrimesPerTract.shape

(2127, 83)

In [149]:
##df_ML_NYC_withTotalTreesandCrimesPerTract
df_ML_NYC_withTotalTreesandCrimesPerTract.to_csv("NYC_Census_Trees_Crimes_Mar8th_3.csv")
df_ML_NYC_withTotalTreesandCrimesPerTract.to_excel("NYC_Census_Trees_Crimes_Mar8th_3.xlsx")

In [79]:
_3

In [80]:
##url for NYC shape file for NTA areas https://query.data.world/s/czne47phgdydklhmvzfpjmgsmz4o6b
url_NewYorkNTA_ShapeDetails = 'https://raw.githubusercontent.com/maireadmanifold/files/main/geo_export_NYC_NTAs.csv'
NewYorkNTA_ShapeDetails = pd.read_csv(url_NewYorkNTA_ShapeDetails, error_bad_lines=False, index_col=0)
NewYorkNTA_ShapeDetails

,boro_name,county_fip,ntacode,ntaname,shape_area,shape_leng
boro_code,,,,,,
3.0,Brooklyn,47,BK88,Borough Park,5.400502e+07,39247.227831
4.0,Queens,81,QN51,Murray Hill,5.248828e+07,33266.904872
4.0,Queens,81,QN27,East Elmhurst,1.972685e+07,19816.712132
3.0,Brooklyn,47,BK95,Erasmus,1.452260e+07,18756.701865
4.0,Queens,81,QN07,Hollis,2.288777e+07,20976.335600
3.0,Brooklyn,47,BK25,Homecrest,2.999197e+07,27514.022918
4.0,Queens,81,QN41,Fresh Meadows-Utopia,2.777485e+07,22106.431272
2.0,Bronx,5,BX33,Longwood,1.073245e+07,18982.129655
3.0,Brooklyn,47,BK43,Midwood,3.579957e+07,27996.590612
4.0,Queens,81,QN08,St. Albans,7.741275e+07,45401.317004
3.0,Brooklyn,47,BK69,Clinton Hill,2.052820e+07,23971.466027
2.0,Bronx,5,BX10,Pelham Bay-Country Club-City Island,4.013453e+07,138249.436712
4.0,Queens,81,QN33,Cambria Heights,3.307680e+07,26168.270087
3.0,Brooklyn,47,BK93,Starrett City,1.159895e+07,17414.782418
4.0,Queens,81,QN06,Jamaica Estates-Holliswood,4.278998e+07,35465.974931
3.0,Brooklyn,47,BK44,Madison,2.737916e+07,26237.257858
3.0,Brooklyn,47,BK41,Kensington-Ocean Parkway,1.589331e+07,20800.752358
3.0,Brooklyn,47,BK26,Gravesend,3.134195e+07,39922.674156
3.0,Brooklyn,47,BK29,Bensonhurst East,3.577795e+07,33903.245433
3.0,Brooklyn,47,BK72,Williamsburg,1.158999e+07,16874.433846
3.0,Brooklyn,47,BK75,Bedford,3.262979e+07,29992.923800
3.0,Brooklyn,47,BK35,Stuyvesant Heights,3.140694e+07,28239.080771
1.0,Manhattan,61,MN21,Gramercy,7.526914e+06,12096.891174
3.0,Brooklyn,47,BK79,Ocean Hill,2.008991e+07,22494.582090
3.0,Brooklyn,47,BK63,Crown Heights South,1.598989e+07,24192.455940
3.0,Brooklyn,47,BK96,Rugby-Remsen Village,3.270695e+07,30957.854297
2.0,Bronx,5,BX31,Allerton-Pelham Gardens,3.169304e+07,25467.117425
3.0,Brooklyn,47,BK91,East Flatbush-Farragut,3.436086e+07,39201.038379
3.0,Brooklyn,47,BK78,Bushwick South,4.016945e+07,40735.742384
3.0,Brooklyn,47,BK77,Bushwick North,2.492793e+07,26321.626916
4.0,Queens,81,QN20,Ridgewood,5.049518e+07,40608.513200
3.0,Brooklyn,47,BK46,Ocean Parkway South,1.778210e+07,21975.997319
3.0,Brooklyn,47,BK68,Fort Greene,1.648282e+07,19825.521059
4.0,Queens,81,QN68,Queensbridge-Ravenswood-Long Island City,2.331703e+07,27067.652533
2.0,Bronx,5,BX08,West Farms-Bronx River,1.508499e+07,17477.294761
2.0,Bronx,5,BX46,Parkchester,9.184677e+06,12411.788209
2.0,Bronx,5,BX55,Soundview-Bruckner,1.625336e+07,19756.559787
4.0,Queens,81,QN19,Glendale,3.001674e+07,41514.435080
2.0,Bronx,5,BX28,Van Cortlandt Village,2.566613e+07,21945.719980
4.0,Queens,81,QN38,Pomonok-Flushing Heights-Hillcrest,3.883596e+07,30731.592023
1.0,Manhattan,61,MN15,Clinton,1.836215e+07,34481.628773
4.0,Queens,81,QN34,Queens Village,6.953343e+07,41782.401044
4.0,Queens,81,QN21,Middle Village,5.768491e+07,42675.548488
4.0,Queens,81,QN29,Elmhurst,3.267535e+07,36711.336372
3.0,Brooklyn,47,BK85,East New York (Pennsylvania Ave),1.939753e+07,24226.851070
1.0,Manhattan,61,MN40,Upper East Side-Carnegie Hill,2.006536e+07,23778.410362
2.0,Bronx,5,BX62,Woodlawn-Wakefield,3.973879e+07,38694.040706
2.0,Bronx,5,BX07,Bronxdale,1.518545e+07,17432.176112
4.0,Queens,81,QN55,South Ozone Park,8.246139e+07,36708.169355
3.0,Brooklyn,47,BK27,Bath Beach,2.053462e+07,22383.743233
3.0,Brooklyn,47,BK28,Bensonhurst West,4.667057e+07,37137.439170
4.0,Queens,81,QN30,Maspeth,3.563316e+07,41265.643307
5.0,Staten Island,85,SI48,Arden Heights,5.041082e+07,29689.395531
4.0,Queens,81,QN50,Elmhurst-Maspeth,2.192767e+07,32362.825201
4.0,Queens,81,QN23,College Point,5.055398e+07,59454.749742
3.0,Brooklyn,47,BK73,North Side-South Side,2.886977e+07,28149.980023
2.0,Bronx,5,BX98,Rikers Island,1.816383e+07,18898.116279
3.0,Brooklyn,47,BK81,Brownsville,3.271937e+07,27298.850097
2.0,Bronx,5,BX52,Schuylerville-Throgs Neck-Edgewater Park,8.843996e+07,91304.794806
5.0,Staten Island,85,SI01,Annadale-Huguenot-Prince's Bay-Eltingville,1.410578e+08,71174.583010
1.0,Manhattan,61,MN25,Battery Park City-Lower Manhattan,1.901430e+07,43738.496041
1.0,Manhattan,61,MN14,Lincoln Square,1.580559e+07,19869.908314
1.0,Manhattan,61,MN17,Midtown-Midtown South,3.019153e+07,27032.700221
3.0,Brooklyn,47,BK60,Prospect Lefferts Gardens-Wingate,3.163897e+07,29562.442410
2.0,Bronx,5,BX26,Highbridge,1.645764e+07,18506.310193
3.0,Brooklyn,47,BK21,Seagate-Coney Island,3.878203e+07,51874.955544
3.0,Brooklyn,47,BK40,Windsor Terrace,1.404167e+07,19033.671737
3.0,Brooklyn,47,BK50,Canarsie,8.209886e+07,43718.666516
2.0,Bronx,5,BX22,North Riverdale-Fieldston-Riverdale,4.904828e+07,31851.142455
2.0,Bronx,5,BX29,Spuyten Duyvil-Kingsbridge,2.321411e+07,27990.788394
3.0,Brooklyn,47,BK42,Flatbush,4.525481e+07,38737.853213
3.0,Brooklyn,47,BK58,Flatlands,5.434178e+07,40635.275342
4.0,Queens,81,QN45,Douglas Manor-Douglaston-Little Neck,6.839417e+07,45784.458107
2.0,Bronx,5,BX09,Soundview-Castle Hill-Clason Point-Harding Park,5.198380e+07,67340.979385
3.0,Brooklyn,47,BK09,Brooklyn Heights-Cobble Hill,9.983620e+06,14264.786528
3.0,Brooklyn,47,BK37,Park Slope-Gowanus,4.250923e+07,31476.808582
5.0,Staten Island,85,SI11,Charleston-Richmond Valley-Tottenville,1.456746e+08,84848.455122
5.0,Staten Island,85,SI32,Rossville-Woodrow,6.496336e+07,33247.258914
1.0,Manhattan,61,MN03,Central Harlem North-Polo Grounds,2.540348e+07,27983.884040
1.0,Manhattan,61,MN32,Yorkville,1.360206e+07,17998.720613
4.0,Queens,81,QN48,Auburndale,3.416492e+07,32452.059674
4.0,Queens,81,QN52,East Flushing,2.945368e+07,25848.545417
2.0,Bronx,5,BX35,Morrisania-Melrose,1.689175e+07,27740.846254
1.0,Manhattan,61,MN01,Marble Hill-Inwood,1.773269e+07,31844.409421
1.0,Manhattan,61,MN13,Hudson Yards-Chelsea-Flatiron-Union Square,3.706838e+07,45693.074601
3.0,Brooklyn,47,BK23,West Brighton,8.738769e+06,14113.581354
1.0,Manhattan,61,MN23,West Village,2.497065e+07,28621.651152
1.0,Manhattan,61,MN12,Upper West Side,3.437994e+07,29160.206532
2.0,Bronx,5,BX43,Norwood,1.572493e+07,22150.308220
2.0,Bronx,5,BX05,Bedford Park-Fordham North,1.499888e+07,22565.481193
2.0,Bronx,5,BX40,Fordham South,6.308875e+06,15880.352072
2.0,Bronx,5,BX41,Mount Hope,1.471671e+07,18937.248157
2.0,Bronx,5,BX03,Eastchester-Edenwald-Baychester,4.025679e+07,59164.999307
2.0,Bronx,5,BX13,Co-op City,3.983370e+07,30327.128141
2.0,Bronx,5,BX17,East Tremont,1.925516e+07,29633.136379
3.0,Brooklyn,47,BK17,Sheepshead Bay-Gerritsen Beach-Manhattan Beach,6.334150e+07,91051.033815
5.0,Staten Island,85,SI08,Grymes Hill-Clifton-Fox Hills,3.775255e+07,37119.899593
4.0,Queens,81,QN05,Rosedale,6.156926e+07,64163.725646
5.0,Staten Island,85,SI45,New Dorp-Midland Beach,5.542945e+07,34336.520886
3.0,Brooklyn,47,BK90,East Williamsburg,3.913279e+07,49247.026969
2.0,Bronx,5,BX63,West Concourse,1.937982e+07,28499.044641
5.0,Staten Island,85,SI36,Old Town-Dongan Hills-South Beach,6.700938e+07,41971.582271
3.0,Brooklyn,47,BK38,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,2.847792e+07,32542.899823
3.0,Brooklyn,47,BK45,Georgetown-Marine Park-Bergen Beach-Mill Basin,6.946374e+07,91993.606596
2.0,Bronx,5,BX49,Pelham Parkway,2.303258e+07,25823.036734
3.0,Brooklyn,47,BK33,Carroll Gardens-Columbia Street-Red Hook,4.460138e+07,60820.884759
4.0,Queens,81,QN46,Bayside-Bayside Hills,8.079859e+07,43020.787937
1.0,Manhattan,61,MN04,Hamilton Heights,1.609614e+07,17411.381931
1.0,Manhattan,61,MN33,East Harlem South,1.665069e+07,18624.664808
4.0,Queens,81,QN71,Old Astoria,1.561960e+07,19366.217298
1.0,Manhattan,61,MN99,park-cemetery-etc-Manhattan,9.154335e+07,155354.846333
4.0,Queens,81,QN72,Steinway,5.772446e+07,43563.149386
4.0,Queens,81,QN25,Corona,2.007732e+07,23868.641664
4.0,Queens,81,QN47,Ft. Totten-Bay Terrace-Clearview,4.629259e+07,39625.842636
1.0,Manhattan,61,MN11,Central Harlem South,1.443930e+07,16621.023444
1.0,Manhattan,61,MN34,East Harlem North,2.449490e+07,30603.718884
4.0,Queens,81,QN26,North Corona,1.800389e+07,18429.540235
4.0,Queens,81,QN22,Flushing,3.786507e+07,38362.728121
4.0,Queens,81,QN02,Springfield Gardens North,2.843265e+07,25437.061861
3.0,Brooklyn,47,BK34,Sunset Park East,2.711007e+07,25901.825537
4.0,Queens,81,QN42,Oakland Gardens,5.100968e+07,42410.067713
3.0,Brooklyn,47,BK32,Sunset Park West,4.999002e+07,83323.506183
2.0,Bronx,5,BX30,Kingsbridge Heights,1.316312e+07,21108.810673
2.0,Bronx,5,BX36,University Heights-Morris Heights,2.125549e+07,24100.432040
5.0,Staten Island,85,SI35,New Brighton-Silver Lake,4.713724e+07,30320.374945
5.0,Staten Island,85,SI22,West New Brighton-New Brighton-St. George,5.603045e+07,66054.251684
1.0,Manhattan,61,MN22,East Village,1.089424e+07,13555.232029
4.0,Queens,81,QN37,Kew Gardens Hills,3.788836e+07,33105.724129
5.0,Staten Island,85,SI99,park-cemetery-etc-Staten Island,2.401472e+07,46217.323052
2.0,Bronx,5,BX75,Crotona Park East,1.631064e+07,24773.573674
2.0,Bronx,5,BX27,Hunts Point,4.973956e+07,44690.371912
5.0,Staten Island,85,SI07,Westerleigh,6.325619e+07,41657.425783
1.0,Manhattan,61,MN28,Lower East Side,2.329741e+07,25466.659594
5.0,Staten Island,85,SI28,Port Richmond,3.641989e+07,39040.874859
3.0,Brooklyn,47,BK19,Brighton Beach,1.718014e+07,21060.169544
4.0,Queens,81,QN17,Forest Hills,5.782765e+07,36171.472649
4.0,Queens,81,QN18,Rego Park,1.994181e+07,26675.103444
2.0,Bronx,5,BX44,Williamsbridge-Olinville,3.627561e+07,27332.421857
2.0,Bronx,5,BX99,park-cemetery-etc-Bronx,2.208372e+08,223421.140891
1.0,Manhattan,61,MN20,Murray Hill-Kips Bay,1.448587e+07,24491.310850
4.0,Queens,81,QN60,Kew Gardens,2.049257e+07,21440.868182
5.0,Staten Island,85,SI12,Mariner's Harbor-Arlington-Port Ivory-Granitev...,8.950232e+07,71306.752741
4.0,Queens,81,QN28,Jackson Heights,4.785850e+07,29423.561405
4.0,Queens,81,QN63,Woodside,2.824660e+07,27869.363285
2.0,Bronx,5,BX14,East Concourse-Concourse Village,1.822164e+07,27199.912010
4.0,Queens,81,QN35,Briarwood-Jamaica Hills,2.937737e+07,30029.287465
4.0,Queens,81,QN70,Astoria,3.933602e+07,32534.631791
4.0,Queens,81,QN62,Queensboro Hill,2.654193e+07,30690.301176
1.0,Manhattan,61,MN50,Stuyvesant Town-Cooper Village,5.582244e+06,12021.748591
1.0,Manhattan,61,MN06,Manhattanville,1.064708e+07,17040.685896
4.0,Queens,81,QN53,Woodhaven,3.703412e+07,28046.455432
4.0,Queens,81,QN49,Whitestone,6.905071e+07,61000.929355
3.0,Brooklyn,47,BK76,Greenpoint,3.532200e+07,28914.354980
1.0,Manhattan,61,MN09,Morningside Heights,2.015586e+07,20746.058487
4.0,Queens,81,QN12,Hammels-Arverne-Edgemere,6.189548e+07,83797.482099
4.0,Queens,81,QN15,Far Rockaway-Bayswater,5.415978e+07,48674.161729
1.0,Manhattan,61,MN24,SoHo-TriBeCa-Civic Center-Little Italy,2.503268e+07,26855.031669
3.0,Brooklyn,47,BK61,Crown Heights North,5.162095e+07,35632.332687
1.0,Manhattan,61,MN27,Chinatown,1.450187e+07,20786.255013
2.0,Bronx,5,BX01,Claremont-Bathgate,1.645187e+07,30053.130825
2.0,Bronx,5,BX06,Belmont,1.355942e+07,17117.284009
1.0,Manhattan,61,MN35,Washington Heights North,2.266741e+07,26683.294730
1.0,Manhattan,61,MN36,Washington Heights South,2.309276e+07,22106.054631
3.0,Brooklyn,47,BK64,Prospect Heights,1.022870e+07,15070.562908
2.0,Bronx,5,BX37,Van Nest-Morris Park-Westchester Square,3.630233e+07,42870.302238
2.0,Bronx,5,BX59,Westchester-Unionport,2.394526e+07,26557.319141
2.0,Bronx,5,BX34,Melrose South-Mott Haven North,1.727176e+07,19589.196253
5.0,Staten Island,85,SI25,Oakwood-Oakwood Beach,5.596188e+07,44299.032452
5.0,Staten Island,85,SI54,Great Kills,8.960651e+07,66106.906158
2.0,Bronx,5,BX39,Mott Haven-Port Morris,4.189855e+07,35603.732251
3.0,Brooklyn,47,BK30,Dyker Heights,2.991874e+07,30729.721847
3.0,Brooklyn,47,BK31,Bay Ridge,6.717336e+07,44508.443076
5.0,Staten Island,85,SI05,New Springville-Bloomfield-Travis,3.272902e+08,109065.873453
5.0,Staten Island,85,SI24,Todt Hill-Emerson Hill-Heartland Village-Light...,1.848815e+08,75942.003022
5.0,Staten Island,85,SI14,Grasmere-Arrochar-Ft. Wadsworth,4.093163e+07,39960.974886
4.0,Queens,81,QN43,Bellerose,5.518430e+07,32086.140465
5.0,Staten Island,85,SI37,Stapleton-Rosebank,4.642679e+07,55229.636423
4.0,Queens,81,QN44,Glen Oaks-Floral Park-New Hyde Park,4.566693e+07,33596.462950
4.0,Queens,81,QN01,South Jamaica,3.997193e+07,32122.551954
4.0,Queens,81,QN76,Baisley Park,4.403858e+07,31478.437878
1.0,Manhattan,61,MN19,Turtle Bay-East Midtown,1.738916e+07,21124.053857
4.0,Queens,81,QN66,Laurelton,3.978492e+07,29530.929956
1.0,Manhattan,61,MN31,Lenox Hill-Roosevelt Island,2.150862e+07,39435.144113
4.0,Queens,81,QN31,Hunters Point-Sunnyside-West Maspeth,1.024216e+08,74592.173365
4.0,Queens,81,QN03,Springfield Gardens South-Brookville,4.328870e+07,45322.165207
4.0,Queens,81,QN98,Airport,2.281990e+08,136232.079658
3.0,Brooklyn,47,BK83,Cypress Hills-City Line,2.760982e+07,35564.199650
4.0,Queens,81,QN56,Ozone Park,2.501677e+07,24730.069017
3.0,Brooklyn,47,BK82,East New York,1.170238e+08,87941.073861
4.0,Queens,81,QN57,Lindenwood-Howard Beach,6.456081e+07,79085.707296
3.0,Brooklyn,47,BK99,park-cemetery-etc-Brooklyn,2.253394e+08,385534.318651
4.0,Queens,81,QN54,Richmond Hill,5.097840e+07,33792.465441
4.0,Queens,81,QN61,Jamaica,4.730804e+07,43696.365063
4.0,Queens,81,QN10,Breezy Point-Belle Harbor-Rockaway Park-Broad ...,1.002097e+08,119016.703209
4.0,Queens,81,QN99,park-cemetery-etc-Queens,3.090638e+08,487058.987349

In [219]:
## save as csv file NYC_CSV__Dec9th_before.csv